from enum import Enum


class ConflictType(int, Enum):
    """EchoGTFS conflict type enum."""

    ERROR_DATASOURCE_FAILURE = 1001
    ERROR_NO_ROUTE_FOUND = 1002
    ERROR_NO_STOP_FOUND = 1003
    ERROR_NO_TRIP_FOUND = 1004

    WARNING_IMPLIED_ADDITIONAL_STOP = 2001
    WARNING_IMPLIED_CANCELED_STOP = 2002
    WARNING_WRONG_QUAY = 2003
    WARNING_ROUTE_NO_GLOBAL_ID = 2004
    WARNING_STOP_NO_GLOBAL_ID = 2005
    WARNING_TRIP_NO_GLOBAL_ID = 2006
    WARNING_PREMATURE_DEPARTURE = 2007
