/* ==========================================================================
   LANGUAGES - Translation strings for all supported languages
========================================================================== */

// Global translations object
window.translations = {
  de: {
    // === DASHBOARD ===
    'nav.dashboard': 'Dashboard',
    'dashboard.title': 'Dashboard',
    'dashboard.section.stats': 'Echtzeitstatus',
    'dashboard.section.endpoints': 'GTFS-RT Endpunkte',
    'dashboard.card.alerts': 'Service Alerts',
    'dashboard.card.trips': 'Trip Updates',
    'dashboard.card.vehicles': 'Vehicle Positions',
    'dashboard.metric.active': 'aktiv',
    'dashboard.metric.inactive': '{count} inaktiv',
    'dashboard.endpoints.service_alerts': 'Service Alerts',
    'dashboard.endpoints.trip_updates': 'Trip Updates',
    'dashboard.endpoints.vehicle_positions': 'Vehicle Positions',
    'dashboard.copy.protobuf': 'Protobuf-URL kopieren',
    'dashboard.copy.json': 'JSON-URL kopieren',
    'dashboard.copy.protobuf.short': 'PBF',
    'dashboard.copy.json.short': 'JSON',
    'dashboard.copy.success': 'URL in die Zwischenablage kopiert.',
    'dashboard.copy.error': 'URL konnte nicht kopiert werden.',

    // === LOGIN ===
    'login.title': 'Anmelden',
    'login.subtitle': 'Bitte melden Sie sich an',
    'login.username': 'Benutzername',
    'login.password': 'Passwort',
    'login.button': 'Anmelden',
    'login.button.busy': 'Anmelden …',
    
    // === LOADING & COMMON ===
    'loading.screen': 'Wird geladen',
    'loading.default': 'Wird geladen ...',
    'loading.saving': 'Wird gespeichert...',
    'loading.importing': 'Wird importiert …',
    'loading.exporting': 'Wird exportiert …',
    
    // === COMMON ACTIONS ===
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.close': 'Schließen',
    'common.add': 'Hinzufügen',
    'common.remove': 'Entfernen',
    'common.remove.title': 'Entfernen',
    'common.reset': 'Zurücksetzen',
    'common.view': 'Anzeigen',
    'common.activate': 'Aktivieren',
    'common.deactivate': 'Deaktivieren',
    'common.run': 'Jetzt ausführen',
    'common.import': 'Importieren',
    'common.export': 'Exportieren',
    'common.move_up': 'Nach oben',
    'common.move_down': 'Nach unten',
    
    // === NAVIGATION ===
    'nav.main': 'Hauptnavigation',
    'nav.alerts': 'Meldungen',
    'nav.trips': 'Fahrten',
    'nav.vehicles': 'Fahrzeuge',
    'nav.sources': 'Datenquellen',
    'nav.accounts': 'Accounts',
    'nav.settings': 'Einstellungen',
    'nav.logout': 'Abmelden',
    
    // === TOP BAR ===
    'topbar.language.title': 'Sprache wechseln',
    'topbar.language.label': 'Sprache',
    'topbar.language.de': 'Deutsch',
    'topbar.language.en': 'English',
    'topbar.profile.title': 'Benutzerprofil',
    'topbar.profile.label': 'Benutzerprofil',
    'topbar.profile.change_password': 'Passwort ändern',
    'topbar.logout.title': 'Abmelden',
    'topbar.logout.label': 'Abmelden',
    
    // === ALERTS PANEL ===
    'alerts.title': 'Meldungen',
    'alerts.quickfilter': 'Schnellfilter',
    'alerts.quickfilter.placeholder': 'Suchbegriff eingeben...',
    'alerts.sort.newest': 'neueste zuerst',
    'alerts.sort.oldest': 'älteste zuerst',
    'alerts.sort.title': 'Sortierung umkehren',
    'alerts.filter': 'Filter',
    'alerts.filter.status': 'Status',
    'alerts.filter.status.active': 'aktive Meldungen',
    'alerts.filter.status.inactive': 'inaktive Meldungen',
    'alerts.filter.source': 'Quelle',
    'alerts.filter.source.internal': 'interne Meldungen',
    'alerts.filter.source.external': 'externe Meldungen',
    'alerts.add': '+ Erfassen',
    'alerts.loading': 'Wird geladen ...',
    'alerts.empty': 'Aktuell sind noch keine Meldungen verfügbar.',
    'alerts.empty.filter': 'Keine Meldungen entsprechen dem Filter.',
    'alerts.error.load': 'Fehler beim Laden der Meldungen.',
    'alerts.error.notfound': 'Meldung nicht gefunden.',
    'alerts.badge.internal': 'Intern',
    'alerts.badge.external': 'Extern',
    'alerts.badge.inactive': 'Inaktiv',
    'alerts.status.changed': 'Meldungsstatus geändert.',
    'alerts.created': 'Meldung erstellt.',
    'alerts.updated': 'Meldung aktualisiert.',
    'alerts.deleted': 'Meldung „{name}" wurde gelöscht.',
    'alerts.delete.confirm': 'Meldung „{name}" wirklich löschen? Diese Aktion ist unwiderruflich.',
    'alerts.delete.title': 'Meldung löschen',
    'alerts.title.notitle': 'Keine Überschrift',
    'alerts.title.unnamed': 'Unbenannte Meldung',
    'alerts.resolution.warning': 'Einige Bezüge konnten nicht aufgelöst werden',
    'alerts.pagination.info': 'Seite {current} von {total} ({count} Meldungen)',

    // === TRIPS PANEL ===
    'trips.title': 'Fahrten',
    'trips.field.line': 'Linie',
    'trips.field.gtfs_id': 'GTFS-ID',
    'trips.field.start': 'Start',
    'trips.field.end': 'Ende',
    'trips.sort.title': 'Sortierung ändern',
    'trips.sort.asc': 'nach Start aufsteigend',
    'trips.sort.desc': 'nach Start absteigend',
    'trips.filter.status.active': 'aktive Fahrten',
    'trips.filter.status.inactive': 'inaktive Fahrten',
    'trips.empty': 'Keine Fahrten verfügbar.',
    'trips.empty.filter': 'Keine Fahrten entsprechen dem Filter.',
    'trips.error.load': 'Fehler beim Laden der Fahrten.',
    'trips.pagination.info': 'Seite {current} von {total} ({count} Fahrten)',
    'trips.resolution.warning': 'Fahrt konnte keiner Soll-Fahrt zugeordnet werden',
    'trips.mock.view': 'Details für Linie {line} sind in dieser Vorschau noch nicht verfügbar.',
    'trips.status.activated': 'Fahrt auf Linie {line} wurde aktiviert.',
    'trips.status.deactivated': 'Fahrt auf Linie {line} wurde deaktiviert.',
    'trips.modal.view': 'Fahrtdetails',
    'trips.view.section.trip': 'Fahrt',
    'trips.view.section.stop_events': 'Fahrzeiten',
    'trips.view.trip_id': 'Fahrt-ID',
    'trips.view.route': 'Linie',
    'trips.view.status': 'Status',
    'trips.view.arrival': 'Ankunft',
    'trips.view.departure': 'Abfahrt',
    'trips.view.empty_stop_events': 'Keine Fahrzeiten verfügbar.',
    'trips.schedule.scheduled': 'Planmäßig',
    'trips.schedule.added': 'Zusatzfahrt',
    'trips.schedule.unscheduled': 'Ungeplant',
    'trips.schedule.canceled': 'Ausgefallen',
    'trips.schedule.deleted': 'Gelöscht',
    'trips.schedule.duplicated': 'Verstärkerfahrt',
    'trips.schedule.replacement': 'Ersatzfahrt',
    'trips.schedule.skipped': 'Übersprungen',
    'trips.schedule.no_data': 'Keine Daten',

    // === VEHICLES PANEL ===
    'vehicles.title': 'Fahrzeuge',
    'vehicles.map.aria': 'Karte mit Fahrzeugpositionen',
    'vehicles.filter.status.active': 'aktive Fahrzeuge',
    'vehicles.filter.status.inactive': 'inaktive Fahrzeuge',
    'vehicles.sheet.line': 'Linie / Fahrt: {line} / {trip}',
    'vehicles.sheet.vehicle': 'Fahrzeug: {value}',
    'vehicles.sheet.updated': 'Aktualisiert: {value}',
    'vehicles.time.second_ago': 'vor {count} Sekunde',
    'vehicles.time.seconds_ago': 'vor {count} Sekunden',
    'vehicles.time.minute_ago': 'vor {count} Minute',
    'vehicles.time.minutes_ago': 'vor {count} Minuten',
    'vehicles.wheelchair.accessible': 'Barrierefrei',
    'vehicles.wheelchair.inaccessible': 'Nicht barrierefrei',
    'vehicles.wheelchair.unknown': 'Keine Information zur Barrierefreiheit',
    
    // === ALERTS MODAL (Create/Edit) ===
    'alert.modal.create': 'Neue Meldung erstellen',
    'alert.modal.edit': 'Meldung bearbeiten',
    'alert.modal.view': 'Meldung anzeigen',
    'alert.tabs.basics': 'Grunddaten',
    'alert.tabs.validity': 'Gültigkeit',
    'alert.tabs.references': 'Bezug',
    'alert.tabs.text': 'Text',
    'alert.cause': 'Ursache',
    'alert.effect': 'Auswirkung',
    'alert.severity': 'Schweregrad',
    'alert.active': 'Aktiv',
    'alert.active.yes': '✓ Aktiv',
    'alert.active.no': '✗ Inaktiv',
    'alert.view.status': 'Status',
    'alert.view.source': 'Quelle',
    'alert.view.source.internal': 'Intern (echogtfs)',
    'alert.cause.unknown.cause': 'Unbekannte Ursache',
    'alert.cause.other.cause': 'Sonstige Ursache',
    'alert.cause.technical.problem': 'Technisches Problem',
    'alert.cause.strike': 'Streik',
    'alert.cause.demonstration': 'Demonstration',
    'alert.cause.accident': 'Unfall',
    'alert.cause.holiday': 'Feiertag',
    'alert.cause.weather': 'Wetter',
    'alert.cause.maintenance': 'Wartung',
    'alert.cause.construction': 'Bauarbeiten',
    'alert.cause.police.activity': 'Polizeieinsatz',
    'alert.cause.medical.emergency': 'Medizinischer Notfall',
    'alert.effect.unknown.effect': 'Unbekannte Auswirkung',
    'alert.effect.no.service': 'Kein Service',
    'alert.effect.reduced.service': 'Eingeschränkter Service',
    'alert.effect.significant.delays': 'Erhebliche Verspätungen',
    'alert.effect.detour': 'Umleitung',
    'alert.effect.additional.service': 'Zusätzlicher Service',
    'alert.effect.modified.service': 'Geänderter Service',
    'alert.effect.other.effect': 'Sonstige Auswirkung',
    'alert.effect.stop.moved': 'Haltestelle verlegt',
    'alert.effect.no.effect': 'Keine Auswirkung',
    'alert.effect.accessibility.issue': 'Barrierefreiheitsproblem',
    'alert.severity.unknown.severity': 'Unbekannt',
    'alert.severity.info': 'Info',
    'alert.severity.warning': 'Warnung',
    'alert.severity.severe': 'Schwerwiegend',
    'alert.period.add': 'Zeitraum hinzufügen',
    'alert.period.title': 'Zeitraum {number}',
    'alert.period.type': 'Art des Zeitraums',
    'alert.period.type.impact': 'Gültigkeitszeitraum',
    'alert.period.type.communication': 'Veröffentlichungszeitraum',
    'alert.period.type.impact.short': '(Gültigkeitszeitraum)',
    'alert.period.type.communication.short': '(Veröffentlichungszeitraum)',
    'alert.period.start': 'Startzeit',
    'alert.period.start.label': 'Von (optional)',
    'alert.period.end': 'Endzeit',
    'alert.period.end.label': 'Bis (optional)',
    'alert.entity.add': 'Bezug hinzufügen',
    'alert.entity.title': 'Bezug {number}',
    'alert.entity.agency': 'Unternehmen',
    'alert.entity.route': 'Linie',
    'alert.entity.route_type': 'Linientyp',
    'alert.entity.route_type.placeholder': 'Typ auswählen...',
    'alert.entity.route_type.tram': 'Straßenbahn',
    'alert.entity.route_type.subway': 'U-Bahn',
    'alert.entity.route_type.rail': 'Zug',
    'alert.entity.route_type.bus': 'Bus',
    'alert.entity.route_type.ferry': 'Fähre',
    'alert.entity.route_type.cable_tram': 'Seilbahn',
    'alert.entity.route_type.aerial_lift': 'Gondel',
    'alert.entity.route_type.funicular': 'Standseilbahn',
    'alert.entity.route_type.trolleybus': 'Trolleybus',
    'alert.entity.route_type.monorail': 'Einschienenbahn',
    'alert.entity.direction': 'Fahrtrichtung',
    'alert.entity.direction.label': 'Richtung (optional)',
    'alert.entity.direction.placeholder': 'Richtung auswählen...',
    'alert.entity.direction.outbound': 'Hinfahrt',
    'alert.entity.direction.inbound': 'Rückfahrt',
    'alert.entity.stop': 'Haltestelle',
    'alert.entity.stop.label': 'Haltestelle (optional)',
    'alert.entity.agency.label': 'Unternehmen (optional)',
    'alert.entity.route.label': 'Linie (optional)',
    'alert.entity.route_type.label': 'Linientyp (optional)',
    'alert.entity.invalid.tooltip': 'Bezug konnte nicht aufgelöst werden',
    'alert.entity.label.agency': 'Unternehmen',
    'alert.entity.label.route': 'Linie',
    'alert.entity.label.route_type': 'Linientyp',
    'alert.entity.label.trip': 'Fahrt',
    'alert.entity.all_routes': 'Alle Verbindungen betroffen',
    'alert.period.always_valid': 'Dauerhaft gültig',
    'alert.translation.add': 'Übersetzung hinzufügen',
    'alert.translation.title': 'Übersetzung {number}',
    'alert.translation.language': 'Sprache',
    'alert.translation.language.de': 'Deutsch',
    'alert.translation.language.en': 'English',
    'alert.translation.language.fr': 'Français',
    'alert.translation.language.it': 'Italiano',
    'alert.translation.language.es': 'Español',
    'alert.translation.header': 'Titel',
    'alert.translation.desc': 'Beschreibung (optional)',
    'alert.translation.url': 'URL (optional)',
    'alert.translation.translations': 'Übersetzungen',
    'alert.error.translation_required': 'Bitte mindestens eine Übersetzung mit Titel eingeben.',
    
    // === SOURCES PANEL ===
    'sources.title': 'Datenquellen',
    'sources.add': '+ Hinzufügen',
    'sources.loading': 'Wird geladen ...',
    'sources.empty': 'Keine Datenquellen vorhanden.',
    'sources.error.load': 'Fehler beim Laden',
    'sources.error.notfound': 'Datenquelle nicht gefunden.',
    'sources.select_option': '-- Bitte auswählen --',
    'sources.table.name': 'Name',
    'sources.table.type': 'Typ',
    'sources.table.cron': 'Cron',
    'sources.table.lastrun': 'Letzte Ausführung',
    'sources.badge.inactive': 'Inaktiv',
    'sources.badge.error': 'FEHLER',
    'sources.run.title': 'Jetzt ausführen',
    'sources.run.running': 'Import läuft...',
    'sources.run.disabled': 'Quelle ist deaktiviert',
    'sources.run.started': 'Import von „{name}" wurde gestartet.',
    'sources.run.error.inactive': 'Diese Datenquelle ist deaktiviert und kann nicht ausgeführt werden.',
    'intf.sources.running': 'Datenquelle wird ausgeführt.',
    'intf.sources.completed': 'Ausführung der Datenquelle abgeschlossen.',
    'sources.activated': 'Datenquelle aktiviert.',
    'sources.deactivated': 'Datenquelle deaktiviert.',
    'sources.created': 'Datenquelle erstellt.',
    'sources.updated': 'Datenquelle aktualisiert.',
    'sources.deleted': 'Datenquelle gelöscht.',
    'sources.delete.confirm': 'Möchten Sie die Datenquelle „{name}" wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
    'sources.delete.title': 'Datenquelle löschen',
    'sources.logs.title': 'Logs anzeigen',
    'sources.logs.view': 'Logs',
    
    // === LOGS MODAL ===
    'logs.modal.title': 'Logs: {name}',
    'logs.loading': 'Logs werden geladen...',
    'logs.empty': 'Keine Logs vorhanden.',
    'logs.error.load': 'Fehler beim Laden der Logs.',
    'logs.timestamp': 'Zeitpunkt',
    'logs.endpoint': 'Endpunkt',
    'logs.status': 'Status',
    'logs.size': 'Größe',
    'logs.details': 'Details',
    'logs.details.title': 'Log-Details',
    'logs.details.request_headers': 'Anfrage-Header',
    'logs.details.response_headers': 'Antwort-Header',
    'logs.details.no_headers': 'Keine Header vorhanden',
    'logs.download': 'Herunterladen',
    'logs.download.unavailable': 'Kein Dump verfügbar',
    'logs.download.error': 'Fehler beim Herunterladen der Log-Datei.',
    
    // === SOURCES MODAL ===
    'source.modal.create': 'Neue Datenquelle',
    'source.modal.edit': 'Datenquelle bearbeiten',
    'source.tabs.configuration': 'Konfiguration',
    'source.tabs.mapping': 'Mapping',
    'source.name': 'Name',
    'source.type': 'Adapter-Typ',
    'source.type.placeholder': 'Typ auswählen...',
    'source.cron': 'Cron-Ausdruck (optional)',
    'source.cron.helper': 'z.B. 0 3 * * * für täglich um 3 Uhr',
    'source.invalid_reference_policy': 'Verfahrensweise bei ungültigen Bezügen',
    'source.invalid_reference_policy.helper': 'Definiert, wie mit Objekten umgegangen wird, die auf nicht-existierende GTFS-Objekte verweisen.',
    'source.invalid_reference_policy.not_specified': 'keine Angabe',
    'source.invalid_reference_policy.discard_entire_object': 'gesamtes Objekt verwerfen',
    'source.invalid_reference_policy.discard_invalid': 'ungültige Bezüge verwerfen',
    'source.invalid_reference_policy.discard_invalid_elements': 'ungültige Bezugselemente verwerfen',
    'source.invalid_reference_policy.keep_object_disabled': 'gesamtes Objekt deaktivieren',
    'source.active': 'Aktiv',
    'source.log_dumps': 'Log Dumps',
    'source.inactive.helper': 'Inaktive Datenquellen führen keine Importe durch und deren Objekte werden gelöscht.',
    'source.log_dumps.helper': 'Wenn deaktiviert, werden nur Log-Metadaten gespeichert und keine Antwort-Dumps als Datei abgelegt.',
    'source.error.required': 'Name und Typ sind erforderlich.',
    'source.error.save_first': 'Bitte speichern Sie die Datenquelle zuerst.',
    'source.error.enrichment_value_required': 'Bitte wählen Sie für alle Anreicherungen einen gültigen Wert aus.',
    'source.mapping.type': 'Mapping-Typ',
    'source.mapping.type.agency': 'Unternehmen',
    'source.mapping.type.route': 'Linien',
    'source.mapping.type.stop': 'Haltestellen',
    'source.mapping.add': 'Mapping hinzufügen',
    'source.mapping.export': 'nach CSV exportieren',
    'source.mapping.import': 'aus CSV importieren',
    'source.mapping.empty': 'Keine Mappings für {type} vorhanden.',
    'source.mapping.key': 'Schlüssel',
    'source.mapping.key.placeholder': 'z.B. externer Key',
    'source.mapping.value': 'Wert (Entity ID)',
    'source.mapping.value.placeholder': 'z.B. route_123',
    'source.mapping.exported': '{type}-Mappings erfolgreich exportiert.',
    'source.mapping.imported': '{count} {type}-Mappings erfolgreich importiert.',
    'source.mapping.import.error.size': 'Die Datei ist zu groß. Maximal 10 MB erlaubt.',
    'source.mapping.import.error.format': 'Bitte nur CSV-Dateien hochladen.',
    'source.mapping.import.error': 'Import fehlgeschlagen',
    
    // Source Enrichments
    'source.tabs.enrichment': 'Anreicherung',
    'source.enrichment.type': 'Anreicherungstyp',
    'source.enrichment.type.cause': 'Ursache',
    'source.enrichment.type.effect': 'Auswirkung',
    'source.enrichment.type.severity': 'Schweregrad',
    'source.enrichment.add': 'Wert hinzufügen',
    'source.enrichment.empty': 'Keine Anreicherungen für {type} vorhanden.',
    'source.enrichment.source_field': 'Quellfeld',
    'source.enrichment.source_field.header': 'Titel',
    'source.enrichment.source_field.description': 'Beschreibung',
    'source.enrichment.source_field.header_description': 'Titel & Beschreibung',
    'source.enrichment.key': 'Schlüssel (Text/Regex)',
    'source.enrichment.key.placeholder': 'z.B. Streik|Ausstand',
    'source.enrichment.value': 'Wert',
    'source.enrichment.value.placeholder': 'Wert auswählen...',
    'source.enrichment.sort_order': 'Priorität',
    'source.enrichment.sort_order.placeholder': '0',
    
    // === ACCOUNTS PANEL ===
    'accounts.title': 'Accounts',
    'accounts.add': '+ Neuer Account',
    'accounts.loading': 'Wird geladen ...',
    'accounts.empty': 'Keine Accounts vorhanden.',
    'accounts.error.load': 'Fehler beim Laden der Accounts.',
    'accounts.error.notfound': 'Account nicht gefunden.',
    'accounts.created': 'Account erstellt.',
    'accounts.updated': 'Account aktualisiert.',
    'accounts.deleted': 'Account „{name}" wurde gelöscht.',
    'accounts.delete.confirm': 'Account „{name}" wirklich löschen? Diese Aktion ist unwiderruflich.',
    'accounts.delete.title': 'Account löschen',
    'accounts.table.username': 'Benutzername',
    'accounts.table.email': 'E-Mail',
    'accounts.table.role': 'Rolle',
    'accounts.table.status': 'Status',
    'accounts.role.admin': 'Admin',
    'accounts.role.poweruser': 'Poweruser',
    'accounts.role.standard': 'Standard',
    'accounts.status.active': 'Aktiv',
    'accounts.status.inactive': 'Inaktiv',
    'accounts.edit.tooltip': 'Bearbeiten',
    'accounts.edit.aria': 'Account {name} bearbeiten',
    'accounts.delete.tooltip': 'Löschen',
    'accounts.delete.aria': 'Account {name} löschen',
    
    // === ACCOUNTS MODAL ===
    'account.modal.create': 'Neuer Account',
    'account.modal.edit': 'Account bearbeiten',
    'account.username': 'Benutzername',
    'account.email': 'E-Mail',
    'account.password': 'Passwort',
    'account.password.hint.create': '',
    'account.password.hint.edit': 'Leer lassen, um bestehendes Passwort beizubehalten',
    'account.active': 'Aktiv',
    'account.superuser': 'Admin',
    'account.poweruser': 'Poweruser',
    'account.chip.active': 'Aktiv',
    'account.chip.admin': 'Admin',
    'account.chip.poweruser': 'Poweruser',
    'account.chip.standard': 'Standard',
    'account.error.email_required': 'Bitte E-Mail eingeben.',
    'account.error.username_required': 'Bitte Benutzername eingeben.',
    'account.error.password_required': 'Bitte Passwort eingeben.',
    
    // === PASSWORD CHANGE MODAL ===
    'password.modal.title': 'Passwort ändern',
    'password.current': 'Aktuelles Passwort',
    'password.new': 'Neues Passwort',
    'password.new_repeat': 'Neues Passwort wiederholen',
    'password.error.current_required': 'Bitte aktuelles Passwort eingeben.',
    'password.error.new_required': 'Bitte neues Passwort eingeben.',
    'password.error.repeat_required': 'Bitte neues Passwort wiederholen.',
    'password.error.mismatch': 'Die neuen Passwörter stimmen nicht überein.',
    'password.error.current_incorrect': 'Das aktuelle Passwort ist falsch.',
    'password.success': 'Passwort wurde erfolgreich geändert.',
    
    // === SETTINGS PANEL ===
    'settings.title': 'Einstellungen',
    'settings.section.general': 'Allgemein',
    'settings.section.appearance': 'Erscheinungsbild',
    'settings.section.language': 'Sprache',
    'settings.section.gtfs_realtime': 'GTFS-Realtime',
    'settings.section.gtfs_feed': 'GTFS-Feed',
    'settings.app_title': 'App-Titel',
    'settings.color_primary': 'Primärfarbe',
    'settings.color_primary.aria': 'Primärfarbe (Hex)',
    'settings.color_secondary': 'Sekundärfarbe',
    'settings.color_secondary.aria': 'Sekundärfarbe (Hex)',
    'settings.language': 'Sprache',
    'settings.language.de': 'Deutsch',
    'settings.language.en': 'English',
    'settings.gtfs_rt_service_alerts_path': 'GTFS-RT ServiceAlerts Pfad',
    'settings.gtfs_rt_service_alerts_path.helper': 'Pfad ohne /api/ Präfix, z.B. realtime/service-alerts.pbf',
    'settings.gtfs_rt_trip_updates_path': 'GTFS-RT TripUpdates Pfad',
    'settings.gtfs_rt_trip_updates_path.helper': 'Pfad ohne /api/ Präfix, z.B. realtime/trip-updates.pbf',
    'settings.gtfs_rt_vehicle_positions_path': 'GTFS-RT VehiclePositions Pfad',
    'settings.gtfs_rt_vehicle_positions_path.helper': 'Pfad ohne /api/ Präfix, z.B. realtime/vehicle-positions.pbf',
    'settings.gtfs_rt_username': 'Basic Auth Benutzername (optional)',
    'settings.gtfs_rt_username.helper': 'Beide Felder löschen, um Basic Auth zu deaktivieren',
    'settings.gtfs_rt_password': 'Basic Auth Passwort (optional)',
    'settings.gtfs_rt_password.helper': 'Leer lassen für neues Passwort oder altes Passwort behalten',
    'settings.reset': 'Zurücksetzen',
    'settings.save': 'Speichern',
    'settings.saved': 'Einstellungen gespeichert.',
    'settings.reset.confirm': 'Möchten Sie wirklich alle Einstellungen auf die Standardwerte zurücksetzen?',
    'settings.reset.title': 'Einstellungen zurücksetzen',
    'settings.reset.done': 'Einstellungen zurückgesetzt.',
    'settings.gtfs_url': 'Feed-URL (GTFS Static ZIP)',
    'settings.gtfs_cron': 'Cron-Ausdruck für automatischen Import',
    'settings.gtfs_cron.helper': 'z.B. 0 3 * * * für täglich um 3 Uhr',
    'settings.gtfs_import': 'Importieren',
    'settings.gtfs_save': 'Speichern',
    'settings.gtfs_url_saved': 'Feed-URL und Cron gespeichert.',
    'settings.gtfs_import_running': 'Import läuft …',
    'settings.gtfs_import_success': 'GTFS-Import erfolgreich abgeschlossen.',
    'settings.gtfs_import_error': 'GTFS-Import fehlgeschlagen. Siehe Status-Details.',
    'settings.gtfs_import_last': 'Letzter Import: {time}',
    'settings.gtfs_import_last_short': 'Letzter Import: {time}',
    'settings.gtfs_import_error_time': 'Fehler ({time}): {message}',
    'settings.gtfs_import_error_short': 'Fehler: {message}',
    'settings.gtfs_import_none': 'Noch kein Import durchgeführt.',
    'settings.gtfs_import_url_required': 'Bitte zuerst eine gültige Feed-URL eingeben.',
    'settings.section.system_copy': 'Systemkopie',
    'settings.system_copy.description': 'Wählen Sie die Datenbereiche für die Systemkopie und starten Sie den Export oder importieren Sie eine Systemkopie.',
    'settings.system_copy.options': 'Zu exportierende Bereiche',
    'settings.system_copy.system_settings': 'Systemeinstellungen',
    'settings.system_copy.gtfs_settings': 'GTFS-Einstellungen',
    'settings.system_copy.users': 'Benutzer',
    'settings.system_copy.datasources': 'Datenquellen (inkl. Mapping und Anreicherung)',
    'settings.system_copy.export': 'Exportieren',
    'settings.system_copy.import': 'Importieren',
    'settings.system_copy.selection_required': 'Bitte mindestens einen Bereich für den Export auswählen.',
    'settings.system_copy.export_running': 'Systemkopie wird exportiert …',
    'settings.system_copy.export_success': 'Systemkopie erfolgreich exportiert.',
    'settings.system_copy.export_error': 'Systemkopie-Export fehlgeschlagen.',
    'settings.system_copy.import_running': 'Systemkopie wird importiert …',
    'settings.system_copy.import_success': 'Systemkopie erfolgreich importiert.',
    'settings.system_copy.import_success_summary': 'Import abgeschlossen: {created} erstellt, {updated} aktualisiert, {remapped} umgeschlüsselt.',
    'settings.system_copy.import_error': 'Systemkopie-Import fehlgeschlagen.',
    'settings.system_copy.import_file_invalid': 'Bitte eine gültige ZIP-Datei auswählen.',
    'intf.gtfsimport.downloading': 'GTFS-Daten wird heruntergeladen',
    'intf.gtfsimport.parsing': 'GTFS-Daten werden gelesen',
    'intf.gtfsimport.mapping.agencies': 'Unternehmen werden verarbeitet',
    'intf.gtfsimport.mapping.stops': 'Haltestellen werden verarbeitet',
    'intf.gtfsimport.mapping.routes': 'Linien werden verarbeitet',
    'intf.gtfsimport.mapping.trips': 'Fahrten werden verarbeitet',
    'intf.gtfsimport.mapping.stop_times': 'Fahrzeiten werden verarbeitet',
    'intf.gtfsimport.completing': 'Daten werden vervollständigt',
    'intf.gtfsimport.clearing': 'Veraltete GTFS-Daten werden gelöscht',
    'intf.gtfsimport.inserting': 'Neue GTFS-Daten werden gespeichert',
    'intf.gtfsimport.done': 'Import abgeschlossen',
    'intf.gtfsimport.error': 'Import mit Fehler abgeschlossen',
    'settings.section.cleanup': 'Datenbereinigung',
    'settings.cleanup_cron': 'Cron-Ausdruck für Datenbereinigung',
    'settings.cleanup_cron.helper': 'z.B. */10 * * * * für alle 10 Minuten',
    'settings.cleanup_policy': 'Verfahrensweise bei abgelaufenen Objekten',
    'settings.cleanup_policy.deactivate': 'Deaktivieren',
    'settings.cleanup_policy.delete': 'Löschen',
    'settings.cleanup_delete_days': 'Endgültiges Löschen',
    'settings.cleanup_delete_days.never': 'Niemals',
    'settings.cleanup_delete_days.1': 'Nach 1 Tag',
    'settings.cleanup_delete_days.7': 'Nach 7 Tagen',
    'settings.cleanup_delete_days.30': 'Nach 30 Tagen',
    'settings.cleanup_info': 'Die Datenbereinigung gilt nur für interne Objekte und Logs von Datenquellen. Objekte von externen Datenquellen werden immer ausgehend von ihrer Datenquelle synchronisiert.',
    
    // === CONFIRM MODAL ===
    'confirm.title': 'Bestätigung erforderlich',
    'confirm.cancel': 'Abbrechen',
    'confirm.ok': 'Löschen',
    
    // === ERRORS (API) ===
    'error.invalid_credentials': 'Ungültige Anmeldedaten.',
    'error.user_not_found': 'Benutzer nicht gefunden.',
    'error.user_exists': 'Benutzer existiert bereits.',
    'error.required_fields': 'Erforderliche Felder fehlen.',
    'error.invalid_email': 'Ungültiges E-Mail-Format.',
    'error.password_short': 'Passwort zu kurz.',
    'error.current_password_incorrect': 'Das aktuelle Passwort ist falsch.',
    'error.access_denied': 'Zugriff verweigert.',
    'error.source_not_found': 'Datenquelle nicht gefunden.',
    'error.invalid_cron': 'Ungültiger Cron-Ausdruck.',
    'error.cron_minute_only': 'Cron-Ausdrücke mit Sekunden werden bei dieser Funktion nicht unterstützt. Bitte einen minutenbasierten Ausdruck mit 5 Feldern verwenden.',
    'error.alert_not_found': 'Meldung nicht gefunden.',
    'error.cannot_delete_external': 'Externe Meldungen können nicht gelöscht werden.',
    'error.invalid_period': 'Ungültiger Aktivierungszeitraum.',
    'error.missing_translation': 'Übersetzung fehlt.',
    'error.invalid_entity': 'Ungültiger Bezug.',
    'error.invalid_input': 'Die Eingabedaten sind ungültig. Bitte überprüfen Sie Ihre Eingaben.',
    'error.conflict': 'Konflikt: Die angeforderte Änderung ist nicht möglich.',
    'error.server_500': 'Interner Serverfehler. Bitte versuchen Sie es später erneut.',
    'error.server_503': 'Der Server ist vorübergehend nicht verfügbar.',
    'error.request_failed': 'Anfrage fehlgeschlagen.',
    'error.server_error': 'Serverfehler. Bitte wenden Sie sich an den Administrator.',
    'error.unknown': 'Ein unbekannter Fehler ist aufgetreten.',
    'error.network': 'Der Server ist nicht erreichbar. Bitte überprüfen Sie Ihre Internetverbindung.',
    
    // === PLACEHOLDERS ===
    'placeholder.empty': 'Keine Einträge vorhanden.',
    
    // === ADAPTER CONFIGS ===
    // GTFS-Realtime Adapter
    'adapter.gtfsrt.endpoint.label': 'Endpoint URL',
    'adapter.gtfsrt.endpoint.placeholder': 'https://api.example.com/gtfs-realtime',
    'adapter.gtfsrt.endpoint.help_text': 'URL zum GTFS-Realtime Protobuf Feed',
    'adapter.gtfsrt.token.label': 'API Token (optional)',
    'adapter.gtfsrt.token.placeholder': 'Bearer-Token oder API-Key',
    'adapter.gtfsrt.token.help_text': 'Authentifizierungs-Token für die API (falls erforderlich)',
    'adapter.gtfsrt.dialect.label': 'Dialekt',
    'adapter.gtfsrt.dialect.help_text': 'GTFS-Realtime Implementierungsvariante',
    'adapter.gtfsrt.dialect.option.gtfsrt_servicealerts': 'GTFS-RT ServiceAlerts',
    
    // SIRI-Lite Adapter
    'adapter.sirilite.endpoint.label': 'Endpoint URL',
    'adapter.sirilite.endpoint.placeholder': 'https://api.example.com/siri-lite',
    'adapter.sirilite.endpoint.help_text': 'URL zum SIRI-Lite Feed',
    'adapter.sirilite.token.label': 'API Token (optional)',
    'adapter.sirilite.token.placeholder': 'Bearer-Token oder API-Key',
    'adapter.sirilite.token.help_text': 'Authentifizierungs-Token für die API (falls erforderlich)',
    'adapter.sirilite.dialect.label': 'Dialekt',
    'adapter.sirilite.dialect.help_text': 'Regionale Implementierungsvariante',
    'adapter.sirilite.dialect.option.sirisx_swiss': 'SIRI-SX Swiss',
    'adapter.sirilite.dialect.option.sirisx': 'SIRI-SX',
    'adapter.sirilite.dialect.option.siriet': 'SIRI-ET',
    'adapter.sirilite.filter.label': 'Filter',
    'adapter.sirilite.filter.placeholder': 'Optionaler Filter-Ausdruck',
    'adapter.sirilite.filter.help_text': 'Filter zur Einschränkung der Datenquelle',

    // SIRI-ET Adapter
    'adapter.siriet.endpoint.label': 'Endpoint URL',
    'adapter.siriet.endpoint.placeholder': 'https://api.example.com/siri-et',
    'adapter.siriet.endpoint.help_text': 'URL zum SIRI-ET Feed',
    'adapter.siriet.participantref.label': 'Participant Reference',
    'adapter.siriet.participantref.placeholder': 'YOUR_PARTICIPANT_ID',
    'adapter.siriet.participantref.help_text': 'Leitstellenkennung',
    'adapter.siriet.method.label': 'Methode',
    'adapter.siriet.method.help_text': 'Anfrage-Methode (Request/Response oder Publish/Subscribe)',
    'adapter.siriet.method.option.request_response': 'Request/Response',
    'adapter.siriet.method.option.publish_subscribe': 'Publish/Subscribe',
    'adapter.siriet.dialect.label': 'Dialekt',
    'adapter.siriet.dialect.help_text': 'SIRI-ET Implementierungsvariante',
    'adapter.siriet.dialect.option.siriet': 'SIRI-ET',
    'adapter.siriet.filter.label': 'Filter',
    'adapter.siriet.filter.placeholder': 'Optionaler Filter-Ausdruck',
    'adapter.siriet.filter.help_text': 'Filter zur Einschränkung der Datenquelle',

    // SIRI-ET Adapter
    'adapter.siriet.endpoint.label': 'Endpoint URL',
    'adapter.siriet.endpoint.placeholder': 'https://api.example.com/siri-et',
    'adapter.siriet.endpoint.help_text': 'URL zum SIRI-ET Feed',
    'adapter.siriet.participantref.label': 'Participant Reference',
    'adapter.siriet.participantref.placeholder': 'YOUR_PARTICIPANT_ID',
    'adapter.siriet.participantref.help_text': 'Leitstellenkennung',
    'adapter.siriet.method.label': 'Methode',
    'adapter.siriet.method.help_text': 'Anfrage-Methode (Request/Response oder Publish/Subscribe)',
    'adapter.siriet.method.option.request_response': 'Request/Response',
    'adapter.siriet.method.option.publish_subscribe': 'Publish/Subscribe',
    'adapter.siriet.dialect.label': 'Dialekt',
    'adapter.siriet.dialect.help_text': 'SIRI-ET Implementierungsvariante',
    'adapter.siriet.dialect.option.siriet': 'SIRI-ET',
    'adapter.siriet.filter.label': 'Filter',
    'adapter.siriet.filter.placeholder': 'Optionaler Filter-Ausdruck',
    'adapter.siriet.filter.help_text': 'Filter zur Einschränkung der Datenquelle',
    
    // SIRI-SX Adapter
    'adapter.sirisx.endpoint.label': 'Endpoint URL',
    'adapter.sirisx.endpoint.placeholder': 'https://api.example.com/siri-sx?RequestorRef={participantRef}',
    'adapter.sirisx.endpoint.help_text': 'URL zum SIRI-SX Feed',
    'adapter.sirisx.participantref.label': 'Participant Reference',
    'adapter.sirisx.participantref.placeholder': 'YOUR_PARTICIPANT_ID',
    'adapter.sirisx.participantref.help_text': 'Leitstellenkennung',
    'adapter.sirisx.method.label': 'Methode',
    'adapter.sirisx.method.help_text': 'Anfrage-Methode (Request/Response oder Publish/Subscribe)',
    'adapter.sirisx.method.option.request_response': 'Request/Response',
    'adapter.sirisx.method.option.publish_subscribe': 'Publish/Subscribe',
    'adapter.sirisx.dialect.label': 'Dialekt',
    'adapter.sirisx.dialect.help_text': 'Regionale Implementierungsvariante (SIRI-SX)',
    'adapter.sirisx.dialect.option.sirisx': 'SIRI-SX',
    'adapter.sirisx.filter.label': 'Filter',
    'adapter.sirisx.filter.placeholder': 'Optionaler Filter-Ausdruck',
    'adapter.sirisx.filter.help_text': 'Filter zur Einschränkung der Datenquelle',
  },
  
  en: {
    // === DASHBOARD ===
    'nav.dashboard': 'Dashboard',
    'dashboard.title': 'Dashboard',
    'dashboard.section.stats': 'Realtime status',
    'dashboard.section.endpoints': 'GTFS-RT endpoints',
    'dashboard.card.alerts': 'Service Alerts',
    'dashboard.card.trips': 'Trip Updates',
    'dashboard.card.vehicles': 'Vehicle Positions',
    'dashboard.metric.active': 'active',
    'dashboard.metric.inactive': '{count} inactive',
    'dashboard.endpoints.service_alerts': 'Service Alerts',
    'dashboard.endpoints.trip_updates': 'Trip Updates',
    'dashboard.endpoints.vehicle_positions': 'Vehicle Positions',
    'dashboard.copy.protobuf': 'Copy Protobuf URL',
    'dashboard.copy.json': 'Copy JSON URL',
    'dashboard.copy.protobuf.short': 'PBF',
    'dashboard.copy.json.short': 'JSON',
    'dashboard.copy.success': 'URL copied to clipboard.',
    'dashboard.copy.error': 'Could not copy URL.',

    // === LOGIN ===
    'login.title': 'Sign In',
    'login.subtitle': 'Please sign in',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.button': 'Sign In',
    'login.button.busy': 'Signing in…',
    
    // === LOADING & COMMON ===
    'loading.screen': 'Loading',
    'loading.default': 'Loading...',
    'loading.saving': 'Saving...',
    'loading.importing': 'Importing…',
    'loading.exporting': 'Exporting…',
    
    // === COMMON ACTIONS ===
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.remove.title': 'Remove',
    'common.reset': 'Reset',
    'common.view': 'View',
    'common.activate': 'Activate',
    'common.deactivate': 'Deactivate',
    'common.run': 'Run now',
    'common.import': 'Import',
    'common.export': 'Export',
    'common.move_up': 'Move up',
    'common.move_down': 'Move down',
    
    // === NAVIGATION ===
    'nav.main': 'Main navigation',
    'nav.alerts': 'Alerts',
    'nav.trips': 'Trips',
    'nav.vehicles': 'Vehicles',
    'nav.sources': 'Data Sources',
    'nav.accounts': 'Accounts',
    'nav.settings': 'Settings',
    'nav.logout': 'Sign Out',
    
    // === TOP BAR ===
    'topbar.language.title': 'Switch language',
    'topbar.language.label': 'Language',
    'topbar.language.de': 'Deutsch',
    'topbar.language.en': 'English',
    'topbar.profile.title': 'User profile',
    'topbar.profile.label': 'User profile',
    'topbar.profile.change_password': 'Change password',
    'topbar.logout.title': 'Sign Out',
    'topbar.logout.label': 'Sign Out',
    
    // === ALERTS PANEL ===
    'alerts.title': 'Alerts',
    'alerts.quickfilter': 'Quick filter',
    'alerts.quickfilter.placeholder': 'Enter search term...',
    'alerts.sort.newest': 'newest first',
    'alerts.sort.oldest': 'oldest first',
    'alerts.sort.title': 'Reverse sort order',
    'alerts.filter': 'Filter',
    'alerts.filter.status': 'Status',
    'alerts.filter.status.active': 'active alerts',
    'alerts.filter.status.inactive': 'inactive alerts',
    'alerts.filter.source': 'Source',
    'alerts.filter.source.internal': 'internal alerts',
    'alerts.filter.source.external': 'external alerts',
    'alerts.add': '+ Create',
    'alerts.loading': 'Loading...',
    'alerts.empty': 'No alerts available yet.',
    'alerts.empty.filter': 'No alerts match the filter.',
    'alerts.error.load': 'Error loading alerts.',
    'alerts.error.notfound': 'Alert not found.',
    'alerts.badge.internal': 'Internal',
    'alerts.badge.external': 'External',
    'alerts.badge.inactive': 'Inactive',
    'alerts.status.changed': 'Alert status changed.',
    'alerts.created': 'Alert created.',
    'alerts.updated': 'Alert updated.',
    'alerts.deleted': 'Alert "{name}" has been deleted.',
    'alerts.delete.confirm': 'Really delete alert "{name}"? This action cannot be undone.',
    'alerts.delete.title': 'Delete Alert',
    'alerts.title.notitle': 'No title',
    'alerts.title.unnamed': 'Unnamed Alert',
    'alerts.resolution.warning': 'Some references could not be resolved',
    'alerts.pagination.info': 'Page {current} of {total} ({count} alerts)',

    // === TRIPS PANEL ===
    'trips.title': 'Trips',
    'trips.field.line': 'Line',
    'trips.field.gtfs_id': 'GTFS ID',
    'trips.field.start': 'Start',
    'trips.field.end': 'End',
    'trips.sort.title': 'Change sort order',
    'trips.sort.asc': 'sort by start ascending',
    'trips.sort.desc': 'sort by start descending',
    'trips.filter.status.active': 'active trips',
    'trips.filter.status.inactive': 'inactive trips',
    'trips.empty': 'No trips available.',
    'trips.empty.filter': 'No trips match the filter.',
    'trips.error.load': 'Error loading trips.',
    'trips.pagination.info': 'Page {current} of {total} ({count} trips)',
    'trips.resolution.warning': 'Trip could not be matched to a nominal trip',
    'trips.mock.view': 'Details for line {line} are not available in this preview yet.',
    'trips.status.activated': 'Trip on line {line} has been activated.',
    'trips.status.deactivated': 'Trip on line {line} has been deactivated.',
    'trips.modal.view': 'Trip Details',
    'trips.view.section.trip': 'Trip',
    'trips.view.section.stop_events': 'Travel Times',
    'trips.view.trip_id': 'Trip ID',
    'trips.view.route': 'Line',
    'trips.view.status': 'Status',
    'trips.view.arrival': 'Arrival',
    'trips.view.departure': 'Departure',
    'trips.view.empty_stop_events': 'No travel times available.',
    'trips.schedule.scheduled': 'Scheduled',
    'trips.schedule.added': 'Added',
    'trips.schedule.unscheduled': 'Unscheduled',
    'trips.schedule.canceled': 'Canceled',
    'trips.schedule.deleted': 'Deleted',
    'trips.schedule.duplicated': 'Duplicated',
    'trips.schedule.replacement': 'Replacement',
    'trips.schedule.skipped': 'Skipped',
    'trips.schedule.no_data': 'No data',

    // === VEHICLES PANEL ===
    'vehicles.title': 'Vehicles',
    'vehicles.map.aria': 'Map with vehicle positions',
    'vehicles.filter.status.active': 'active vehicles',
    'vehicles.filter.status.inactive': 'inactive vehicles',
    'vehicles.sheet.line': 'Line / Trip: {line} / {trip}',
    'vehicles.sheet.vehicle': 'Vehicle: {value}',
    'vehicles.sheet.updated': 'Updated: {value}',
    'vehicles.time.second_ago': '{count} second ago',
    'vehicles.time.seconds_ago': '{count} seconds ago',
    'vehicles.time.minute_ago': '{count} minute ago',
    'vehicles.time.minutes_ago': '{count} minutes ago',
    'vehicles.wheelchair.accessible': 'Wheelchair accessible',
    'vehicles.wheelchair.inaccessible': 'Not wheelchair accessible',
    'vehicles.wheelchair.unknown': 'No wheelchair accessibility information',
    
    // === ALERTS MODAL (Create/Edit) ===
    'alert.modal.create': 'Create New Alert',
    'alert.modal.edit': 'Edit Alert',
    'alert.modal.view': 'View Alert',
    'alert.tabs.basics': 'Basics',
    'alert.tabs.validity': 'Validity',
    'alert.tabs.references': 'References',
    'alert.tabs.text': 'Text',
    'alert.cause': 'Cause',
    'alert.effect': 'Effect',
    'alert.severity': 'Severity',
    'alert.active': 'Active',
    'alert.active.yes': '✓ Active',
    'alert.active.no': '✗ Inactive',
    'alert.view.status': 'Status',
    'alert.view.source': 'Source',
    'alert.view.source.internal': 'Internal (echogtfs)',
    'alert.cause.unknown.cause': 'Unknown cause',
    'alert.cause.other.cause': 'Other cause',
    'alert.cause.technical.problem': 'Technical problem',
    'alert.cause.strike': 'Strike',
    'alert.cause.demonstration': 'Demonstration',
    'alert.cause.accident': 'Accident',
    'alert.cause.holiday': 'Holiday',
    'alert.cause.weather': 'Weather',
    'alert.cause.maintenance': 'Maintenance',
    'alert.cause.construction': 'Construction',
    'alert.cause.police.activity': 'Police activity',
    'alert.cause.medical.emergency': 'Medical emergency',
    'alert.effect.unknown.effect': 'Unknown effect',
    'alert.effect.no.service': 'No service',
    'alert.effect.reduced.service': 'Reduced service',
    'alert.effect.significant.delays': 'Significant delays',
    'alert.effect.detour': 'Detour',
    'alert.effect.additional.service': 'Additional service',
    'alert.effect.modified.service': 'Modified service',
    'alert.effect.other.effect': 'Other effect',
    'alert.effect.stop.moved': 'Stop moved',
    'alert.effect.no.effect': 'No effect',
    'alert.effect.accessibility.issue': 'Accessibility issue',
    'alert.severity.unknown.severity': 'Unknown',
    'alert.severity.info': 'Info',
    'alert.severity.warning': 'Warning',
    'alert.severity.severe': 'Severe',
    'alert.period.add': 'Add time period',
    'alert.period.title': 'Period {number}',
    'alert.period.type': 'Period type',
    'alert.period.type.impact': 'Impact period',
    'alert.period.type.communication': 'Communication period',
    'alert.period.type.impact.short': '(Impact period)',
    'alert.period.type.communication.short': '(Communication period)',
    'alert.period.start': 'Start time',
    'alert.period.start.label': 'From (optional)',
    'alert.period.end': 'End time',
    'alert.period.end.label': 'To (optional)',
    'alert.entity.add': 'Add reference',
    'alert.entity.title': 'Reference {number}',
    'alert.entity.agency': 'Agency',
    'alert.entity.route': 'Route',
    'alert.entity.route_type': 'Route type',
    'alert.entity.route_type.placeholder': 'Select type...',
    'alert.entity.route_type.tram': 'Tram',
    'alert.entity.route_type.subway': 'Subway',
    'alert.entity.route_type.rail': 'Rail',
    'alert.entity.route_type.bus': 'Bus',
    'alert.entity.route_type.ferry': 'Ferry',
    'alert.entity.route_type.cable_tram': 'Cable tram',
    'alert.entity.route_type.aerial_lift': 'Aerial lift',
    'alert.entity.route_type.funicular': 'Funicular',
    'alert.entity.route_type.trolleybus': 'Trolleybus',
    'alert.entity.route_type.monorail': 'Monorail',
    'alert.entity.direction': 'Direction',
    'alert.entity.direction.label': 'Direction (optional)',
    'alert.entity.direction.placeholder': 'Select direction...',
    'alert.entity.direction.outbound': 'Outbound',
    'alert.entity.direction.inbound': 'Inbound',
    'alert.entity.stop': 'Stop',
    'alert.entity.stop.label': 'Stop (optional)',
    'alert.entity.agency.label': 'Agency (optional)',
    'alert.entity.route.label': 'Route (optional)',
    'alert.entity.route_type.label': 'Route type (optional)',
    'alert.entity.invalid.tooltip': 'Reference could not be resolved',
    'alert.entity.label.agency': 'Agency',
    'alert.entity.label.route': 'Route',
    'alert.entity.label.route_type': 'Route type',
    'alert.entity.label.trip': 'Trip',
    'alert.entity.all_routes': 'All routes affected',
    'alert.period.always_valid': 'Always valid',
    'alert.translation.add': 'Add translation',
    'alert.translation.title': 'Translation {number}',
    'alert.translation.language': 'Language',
    'alert.translation.language.de': 'Deutsch',
    'alert.translation.language.en': 'English',
    'alert.translation.language.fr': 'Français',
    'alert.translation.language.it': 'Italiano',
    'alert.translation.language.es': 'Español',
    'alert.translation.header': 'Title',
    'alert.translation.desc': 'Description (optional)',
    'alert.translation.url': 'URL (optional)',
    'alert.translation.translations': 'Translations',
    'alert.error.translation_required': 'Please enter at least one translation with a title.',
    
    // === SOURCES PANEL ===
    'sources.title': 'Data Sources',
    'sources.add': '+ Add',
    'sources.loading': 'Loading...',
    'sources.empty': 'No data sources available.',
    'sources.error.load': 'Error loading',
    'sources.error.notfound': 'Data source not found.',
    'sources.select_option': '-- Please select --',
    'sources.table.name': 'Name',
    'sources.table.type': 'Type',
    'sources.table.cron': 'Cron',
    'sources.table.lastrun': 'Last run',
    'sources.badge.inactive': 'Inactive',
    'sources.badge.error': 'ERROR',
    'sources.run.title': 'Run now',
    'sources.run.running': 'Import running...',
    'sources.run.disabled': 'Source is disabled',
    'sources.run.started': 'Import of "{name}" has been started.',
    'sources.run.error.inactive': 'This data source is disabled and cannot be run.',
    'intf.sources.running': 'Data source execution started.',
    'intf.sources.completed': 'Data source execution completed.',
    'sources.activated': 'Data source activated.',
    'sources.deactivated': 'Data source deactivated.',
    'sources.created': 'Data source created.',
    'sources.updated': 'Data source updated.',
    'sources.deleted': 'Data source deleted.',
    'sources.delete.confirm': 'Do you really want to delete the data source "{name}"? This action cannot be undone.',
    'sources.delete.title': 'Delete Data Source',
    'sources.logs.title': 'View Logs',
    'sources.logs.view': 'Logs',
    
    // === LOGS MODAL ===
    'logs.modal.title': 'Logs: {name}',
    'logs.loading': 'Loading logs...',
    'logs.empty': 'No logs available.',
    'logs.error.load': 'Error loading logs.',
    'logs.timestamp': 'Timestamp',
    'logs.endpoint': 'Endpoint',
    'logs.status': 'Status',
    'logs.size': 'Size',
    'logs.details': 'Details',
    'logs.details.title': 'Log Details',
    'logs.details.request_headers': 'Request Headers',
    'logs.details.response_headers': 'Response Headers',
    'logs.details.no_headers': 'No headers available',
    'logs.download': 'Download',
    'logs.download.unavailable': 'No dump available',
    'logs.download.error': 'Error downloading log file.',
    
    // === SOURCES MODAL ===
    'source.modal.create': 'New Data Source',
    'source.modal.edit': 'Edit Data Source',
    'source.tabs.configuration': 'Configuration',
    'source.tabs.mapping': 'Mapping',
    'source.name': 'Name',
    'source.type': 'Adapter type',
    'source.type.placeholder': 'Select type...',
    'source.cron': 'Cron expression (optional)',
    'source.cron.helper': 'e.g., 0 3 * * * for daily at 3 AM',
    'source.invalid_reference_policy': 'Invalid reference policy',
    'source.invalid_reference_policy.helper': 'Defines how to handle objects that reference non-existent GTFS objects.',
    'source.invalid_reference_policy.not_specified': 'not specified',
    'source.invalid_reference_policy.discard_entire_object': 'discard entire object',
    'source.invalid_reference_policy.discard_invalid': 'discard invalid references',
    'source.invalid_reference_policy.discard_invalid_elements': 'discard invalid reference elements',
    'source.invalid_reference_policy.keep_object_disabled': 'deactivate entire object',
    'source.active': 'Active',
    'source.log_dumps': 'Log Dumps',
    'source.inactive.helper': 'Inactive data sources do not perform imports and their objects are deleted.',
    'source.log_dumps.helper': 'When disabled, only log metadata is stored and no response dump files are persisted.',
    'source.error.required': 'Name and type are required.',
    'source.error.save_first': 'Please save the data source first.',
    'source.error.enrichment_value_required': 'Please select a valid value for all enrichments.',
    'source.mapping.type': 'Mapping type',
    'source.mapping.type.agency': 'Agencies',
    'source.mapping.type.route': 'Routes',
    'source.mapping.type.stop': 'Stops',
    'source.mapping.add': 'Add mapping',
    'source.mapping.export': 'export to CSV',
    'source.mapping.import': 'import from CSV',
    'source.mapping.empty': 'No mappings for {type} available.',
    'source.mapping.key': 'Key',
    'source.mapping.key.placeholder': 'e.g., external key',
    'source.mapping.value': 'Value (Entity ID)',
    'source.mapping.value.placeholder': 'e.g., route_123',
    'source.mapping.exported': '{type} mappings successfully exported.',
    'source.mapping.imported': '{count} {type} mappings successfully imported.',
    'source.mapping.import.error.size': 'File is too large. Maximum 10 MB allowed.',
    'source.mapping.import.error.format': 'Please upload CSV files only.',
    'source.mapping.import.error': 'Import failed',
    
    // Source Enrichments
    'source.tabs.enrichment': 'Enrichment',
    'source.enrichment.type': 'Enrichment type',
    'source.enrichment.type.cause': 'Cause',
    'source.enrichment.type.effect': 'Effect',
    'source.enrichment.type.severity': 'Severity',
    'source.enrichment.add': 'Add value',
    'source.enrichment.empty': 'No enrichments for {type} available.',
    'source.enrichment.source_field': 'Source field',
    'source.enrichment.source_field.header': 'Title',
    'source.enrichment.source_field.description': 'Description',
    'source.enrichment.source_field.header_description': 'Title & Description',
    'source.enrichment.key': 'Key (text/regex)',
    'source.enrichment.key.placeholder': 'e.g., strike|walkout',
    'source.enrichment.value': 'Value',
    'source.enrichment.value.placeholder': 'Select value...',
    'source.enrichment.sort_order': 'Priority',
    'source.enrichment.sort_order.placeholder': '0',
    
    // === ACCOUNTS PANEL ===
    'accounts.title': 'Accounts',
    'accounts.add': '+ New Account',
    'accounts.loading': 'Loading...',
    'accounts.empty': 'No accounts available.',
    'accounts.error.load': 'Error loading accounts.',
    'accounts.error.notfound': 'Account not found.',
    'accounts.created': 'Account created.',
    'accounts.updated': 'Account updated.',
    'accounts.deleted': 'Account "{name}" has been deleted.',
    'accounts.delete.confirm': 'Really delete account "{name}"? This action cannot be undone.',
    'accounts.delete.title': 'Delete Account',
    'accounts.table.username': 'Username',
    'accounts.table.email': 'Email',
    'accounts.table.role': 'Role',
    'accounts.table.status': 'Status',
    'accounts.role.admin': 'Admin',
    'accounts.role.poweruser': 'Poweruser',
    'accounts.role.standard': 'Standard',
    'accounts.status.active': 'Active',
    'accounts.status.inactive': 'Inactive',
    'accounts.edit.tooltip': 'Edit',
    'accounts.edit.aria': 'Edit account {name}',
    'accounts.delete.tooltip': 'Delete',
    'accounts.delete.aria': 'Delete account {name}',
    
    // === ACCOUNTS MODAL ===
    'account.modal.create': 'New Account',
    'account.modal.edit': 'Edit Account',
    'account.username': 'Username',
    'account.email': 'Email',
    'account.password': 'Password',
    'account.password.hint.create': '',
    'account.password.hint.edit': 'Leave empty to keep existing password',
    'account.active': 'Active',
    'account.superuser': 'Admin',
    'account.poweruser': 'Poweruser',
    'account.chip.active': 'Active',
    'account.chip.admin': 'Admin',
    'account.chip.poweruser': 'Poweruser',
    'account.chip.standard': 'Standard',
    'account.error.email_required': 'Please enter an email.',
    'account.error.username_required': 'Please enter a username.',
    'account.error.password_required': 'Please enter a password.',
    
    // === PASSWORD CHANGE MODAL ===
    'password.modal.title': 'Change Password',
    'password.current': 'Current Password',
    'password.new': 'New Password',
    'password.new_repeat': 'Repeat New Password',
    'password.error.current_required': 'Please enter your current password.',
    'password.error.new_required': 'Please enter a new password.',
    'password.error.repeat_required': 'Please repeat the new password.',
    'password.error.mismatch': 'The new passwords do not match.',
    'password.error.current_incorrect': 'The current password is incorrect.',
    'password.success': 'Password was changed successfully.',
    
    // === SETTINGS PANEL ===
    'settings.title': 'Settings',
    'settings.section.general': 'General',
    'settings.section.appearance': 'Appearance',
    'settings.section.language': 'Language',
    'settings.section.gtfs_realtime': 'GTFS Realtime',
    'settings.section.gtfs_feed': 'GTFS Feed',
    'settings.app_title': 'App Title',
    'settings.color_primary': 'Primary color',
    'settings.color_primary.aria': 'Primary color (Hex)',
    'settings.color_secondary': 'Secondary color',
    'settings.color_secondary.aria': 'Secondary color (Hex)',
    'settings.language': 'Language',
    'settings.language.de': 'Deutsch',
    'settings.language.en': 'English',
    'settings.gtfs_rt_service_alerts_path': 'GTFS-RT ServiceAlerts path',
    'settings.gtfs_rt_service_alerts_path.helper': 'Path without /api/ prefix, e.g., realtime/service-alerts.pbf',
    'settings.gtfs_rt_trip_updates_path': 'GTFS-RT TripUpdates path',
    'settings.gtfs_rt_trip_updates_path.helper': 'Path without /api/ prefix, e.g., realtime/trip-updates.pbf',
    'settings.gtfs_rt_vehicle_positions_path': 'GTFS-RT VehiclePositions path',
    'settings.gtfs_rt_vehicle_positions_path.helper': 'Path without /api/ prefix, e.g., realtime/vehicle-positions.pbf',
    'settings.gtfs_rt_username': 'Basic Auth username (optional)',
    'settings.gtfs_rt_username.helper': 'Clear both fields to disable Basic Auth',
    'settings.gtfs_rt_password': 'Basic Auth password (optional)',
    'settings.gtfs_rt_password.helper': 'Leave empty to set new password or keep old password',
    'settings.reset': 'Reset',
    'settings.save': 'Save',
    'settings.saved': 'Settings saved.',
    'settings.reset.confirm': 'Do you really want to reset all settings to their default values?',
    'settings.reset.title': 'Reset Settings',
    'settings.reset.done': 'Settings reset.',
    'settings.gtfs_url': 'Feed URL (GTFS Static ZIP)',
    'settings.gtfs_cron': 'Cron expression for automatic import',
    'settings.gtfs_cron.helper': 'e.g., 0 3 * * * for daily at 3 AM',
    'settings.gtfs_import': 'Import',
    'settings.gtfs_save': 'Save',
    'settings.gtfs_url_saved': 'Feed URL and cron saved.',
    'settings.gtfs_import_running': 'Import running…',
    'settings.gtfs_import_success': 'GTFS import completed successfully.',
    'settings.gtfs_import_error': 'GTFS import failed. See status details.',
    'settings.gtfs_import_last': 'Last import: {time}',
    'settings.gtfs_import_last_short': 'Last import: {time}',
    'settings.gtfs_import_error_time': 'Error ({time}): {message}',
    'settings.gtfs_import_error_short': 'Error: {message}',
    'settings.gtfs_import_none': 'No import performed yet.',
    'settings.gtfs_import_url_required': 'Please enter a valid feed URL first.',
    'settings.section.system_copy': 'System Copy',
    'settings.system_copy.description': 'Choose which data domains to be exported and start the export or import a system copy.',
    'settings.system_copy.options': 'Domains to export',
    'settings.system_copy.system_settings': 'System settings',
    'settings.system_copy.gtfs_settings': 'GTFS settings',
    'settings.system_copy.users': 'Users',
    'settings.system_copy.datasources': 'Data sources (including mappings and enrichments)',
    'settings.system_copy.export': 'Export',
    'settings.system_copy.import': 'Import',
    'settings.system_copy.selection_required': 'Please select at least one domain for export.',
    'settings.system_copy.export_running': 'Exporting system copy…',
    'settings.system_copy.export_success': 'System copy exported successfully.',
    'settings.system_copy.export_error': 'System copy export failed.',
    'settings.system_copy.import_running': 'Importing system copy…',
    'settings.system_copy.import_success': 'System copy imported successfully.',
    'settings.system_copy.import_success_summary': 'Import complete: {created} created, {updated} updated, {remapped} remapped.',
    'settings.system_copy.import_error': 'System copy import failed.',
    'settings.system_copy.import_file_invalid': 'Please select a valid ZIP file.',
    'intf.gtfsimport.downloading': 'Downloading GTFS data',
    'intf.gtfsimport.parsing': 'Reading GTFS data',
    'intf.gtfsimport.mapping.agencies': 'Processing agencies',
    'intf.gtfsimport.mapping.stops': 'Processing stops',
    'intf.gtfsimport.mapping.routes': 'Processing routes',
    'intf.gtfsimport.mapping.trips': 'Processing trips',
    'intf.gtfsimport.mapping.stop_times': 'Processing stop times',
    'intf.gtfsimport.completing': 'Completing data',
    'intf.gtfsimport.clearing': 'Clearing deprecated GTFS data',
    'intf.gtfsimport.inserting': 'Saving new GTFS data',
    'intf.gtfsimport.done': 'Import completed',
    'intf.gtfsimport.error': 'Import completed with errors',
    'settings.section.cleanup': 'Data Cleanup',
    'settings.cleanup_cron': 'Cron expression for data cleanup',
    'settings.cleanup_cron.helper': 'e.g., */10 * * * * for every 10 minutes',
    'settings.cleanup_policy': 'Policy for expired objects',
    'settings.cleanup_policy.deactivate': 'Deactivate',
    'settings.cleanup_policy.delete': 'Delete',
    'settings.cleanup_delete_days': 'Permanent deletion',
    'settings.cleanup_delete_days.never': 'Never',
    'settings.cleanup_delete_days.1': 'After 1 day',
    'settings.cleanup_delete_days.7': 'After 7 days',
    'settings.cleanup_delete_days.30': 'After 30 days',
    'settings.cleanup_info': 'Data cleanup only applies to internal objects and data source logs. Objects from external data sources are always synchronized from their data source.',
    
    // === CONFIRM MODAL ===
    'confirm.title': 'Confirmation required',
    'confirm.cancel': 'Cancel',
    'confirm.ok': 'Delete',
    
    // === ERRORS (API) ===
    'error.invalid_credentials': 'Invalid credentials.',
    'error.user_not_found': 'User not found.',
    'error.user_exists': 'User already exists.',
    'error.required_fields': 'Required fields are missing.',
    'error.invalid_email': 'Invalid email format.',
    'error.password_short': 'Password too short.',
    'error.current_password_incorrect': 'The current password is incorrect.',
    'error.access_denied': 'Access denied.',
    'error.source_not_found': 'Data source not found.',
    'error.invalid_cron': 'Invalid cron expression.',
    'error.cron_minute_only': 'Cron expressions with seconds are not supported in this function. Please use a minute-based expression with 5 fields.',
    'error.alert_not_found': 'Alert not found.',
    'error.cannot_delete_external': 'External alerts cannot be deleted.',
    'error.invalid_period': 'Invalid time period.',
    'error.missing_translation': 'Translation missing.',
    'error.invalid_entity': 'Invalid reference.',
    'error.invalid_input': 'The input data is invalid. Please check your entries.',
    'error.conflict': 'Conflict: The requested change is not possible.',
    'error.server_500': 'Internal server error. Please try again later.',
    'error.server_503': 'The server is temporarily unavailable.',
    'error.request_failed': 'Request failed.',
    'error.server_error': 'Server error. Please contact the administrator.',
    'error.unknown': 'An unknown error occurred.',
    'error.network': 'The server is not reachable. Please check your internet connection.',
    
    // === PLACEHOLDERS ===
    'placeholder.empty': 'No entries available.',
    
    // === ADAPTER CONFIGS ===
    // GTFS-Realtime Adapter
    'adapter.gtfsrt.endpoint.label': 'Endpoint URL',
    'adapter.gtfsrt.endpoint.placeholder': 'https://api.example.com/gtfs-realtime',
    'adapter.gtfsrt.endpoint.help_text': 'URL to the GTFS-Realtime Protobuf feed',
    'adapter.gtfsrt.token.label': 'API Token (optional)',
    'adapter.gtfsrt.token.placeholder': 'Bearer token or API key',
    'adapter.gtfsrt.token.help_text': 'Authentication token for the API (if required)',
    'adapter.gtfsrt.dialect.label': 'Dialect',
    'adapter.gtfsrt.dialect.help_text': 'GTFS-Realtime implementation variant',
    'adapter.gtfsrt.dialect.option.gtfsrt_servicealerts': 'GTFS-RT ServiceAlerts',
    
    // SIRI-Lite Adapter
    'adapter.sirilite.endpoint.label': 'Endpoint URL',
    'adapter.sirilite.endpoint.placeholder': 'https://api.example.com/siri-lite',
    'adapter.sirilite.endpoint.help_text': 'URL to the SIRI-Lite feed',
    'adapter.sirilite.token.label': 'API Token (optional)',
    'adapter.sirilite.token.placeholder': 'Bearer token or API key',
    'adapter.sirilite.token.help_text': 'Authentication token for the API (if required)',
    'adapter.sirilite.dialect.label': 'Dialect',
    'adapter.sirilite.dialect.help_text': 'Regional implementation variant',
    'adapter.sirilite.dialect.option.sirisx_swiss': 'SIRI-SX Swiss',
    'adapter.sirilite.dialect.option.sirisx': 'SIRI-SX',
    'adapter.sirilite.dialect.option.siriet': 'SIRI-ET',
    'adapter.sirilite.filter.label': 'Filter',
    'adapter.sirilite.filter.placeholder': 'Optional filter expression',
    'adapter.sirilite.filter.help_text': 'Filter to restrict the data source',
    
    // SIRI-SX Adapter
    'adapter.sirisx.endpoint.label': 'Endpoint URL',
    'adapter.sirisx.endpoint.placeholder': 'https://api.example.com/siri-sx?RequestorRef={participantRef}',
    'adapter.sirisx.endpoint.help_text': 'URL to the SIRI-SX feed',
    'adapter.sirisx.participantref.label': 'Participant Reference',
    'adapter.sirisx.participantref.placeholder': 'YOUR_PARTICIPANT_ID',
    'adapter.sirisx.participantref.help_text': 'Participant identifier',
    'adapter.sirisx.method.label': 'Method',
    'adapter.sirisx.method.help_text': 'Request method (Request/Response or Publish/Subscribe)',
    'adapter.sirisx.method.option.request_response': 'Request/Response',
    'adapter.sirisx.method.option.publish_subscribe': 'Publish/Subscribe',
    'adapter.sirisx.dialect.label': 'Dialect',
    'adapter.sirisx.dialect.help_text': 'Regional implementation variant (SIRI-SX)',
    'adapter.sirisx.dialect.option.sirisx': 'SIRI-SX',
    'adapter.sirisx.filter.label': 'Filter',
    'adapter.sirisx.filter.placeholder': 'Optional filter expression',
    'adapter.sirisx.filter.help_text': 'Filter to restrict the data source',
  }
};
