/* ==========================================================================
   LANGUAGES - Translation strings for all supported languages
========================================================================== */

// Global translations object
window.translations = {
  de: {
    // === LOGIN ===
    'login.title': 'Anmelden',
    'login.subtitle': 'Bitte melden Sie sich an',
    'login.username': 'Benutzername',
    'login.password': 'Passwort',
    'login.button': 'Anmelden',
    'login.button.busy': 'Anmelden …',
    
    // === LOADING & COMMON ===
    'loading.screen': 'Wird geladen',
    'loading.default': 'Wird geladen ...',
    'loading.saving': 'Wird gespeichert...',
    'loading.importing': 'Wird importiert …',
    
    // === COMMON ACTIONS ===
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.close': 'Schließen',
    'common.add': 'Hinzufügen',
    'common.remove': 'Entfernen',
    'common.remove.title': 'Entfernen',
    'common.reset': 'Zurücksetzen',
    'common.view': 'Anzeigen',
    'common.activate': 'Aktivieren',
    'common.deactivate': 'Deaktivieren',
    'common.run': 'Jetzt ausführen',
    'common.import': 'Importieren',
    'common.export': 'Exportieren',
    'common.move_up': 'Nach oben',
    'common.move_down': 'Nach unten',
    
    // === NAVIGATION ===
    'nav.main': 'Hauptnavigation',
    'nav.alerts': 'Meldungen',
    'nav.sources': 'Datenquellen',
    'nav.accounts': 'Accounts',
    'nav.settings': 'Einstellungen',
    'nav.logout': 'Abmelden',
    
    // === TOP BAR ===
    'topbar.language.title': 'Sprache wechseln',
    'topbar.language.label': 'Sprache',
    'topbar.language.de': 'Deutsch',
    'topbar.language.en': 'English',
    'topbar.logout.title': 'Abmelden',
    'topbar.logout.label': 'Abmelden',
    
    // === ALERTS PANEL ===
    'alerts.title': 'Meldungen',
    'alerts.quickfilter': 'Schnellfilter',
    'alerts.quickfilter.placeholder': 'Suchbegriff eingeben...',
    'alerts.sort.newest': 'neueste zuerst',
    'alerts.sort.oldest': 'älteste zuerst',
    'alerts.sort.title': 'Sortierung umkehren',
    'alerts.filter': 'Filter',
    'alerts.filter.status': 'Status',
    'alerts.filter.status.active': 'aktive Meldungen',
    'alerts.filter.status.inactive': 'inaktive Meldungen',
    'alerts.filter.source': 'Quelle',
    'alerts.filter.source.internal': 'interne Meldungen',
    'alerts.filter.source.external': 'externe Meldungen',
    'alerts.add': '+ Erfassen',
    'alerts.loading': 'Wird geladen ...',
    'alerts.empty': 'Aktuell sind noch keine Meldungen verfügbar.',
    'alerts.empty.filter': 'Keine Meldungen entsprechen dem Filter.',
    'alerts.error.load': 'Fehler beim Laden der Meldungen.',
    'alerts.error.notfound': 'Meldung nicht gefunden.',
    'alerts.badge.internal': 'Intern',
    'alerts.badge.external': 'Extern',
    'alerts.badge.inactive': 'Inaktiv',
    'alerts.status.changed': 'Meldungsstatus geändert.',
    'alerts.created': 'Meldung erstellt.',
    'alerts.updated': 'Meldung aktualisiert.',
    'alerts.deleted': 'Meldung „{name}" wurde gelöscht.',
    'alerts.delete.confirm': 'Meldung „{name}" wirklich löschen? Diese Aktion ist unwiderruflich.',
    'alerts.delete.title': 'Meldung löschen',
    'alerts.title.notitle': 'Keine Überschrift',
    'alerts.title.unnamed': 'Unbenannte Meldung',
    'alerts.resolution.warning': 'Einige Bezüge konnten nicht aufgelöst werden',
    'alerts.pagination.info': 'Seite {current} von {total} ({count} Meldungen)',
    
    // === ALERTS MODAL (Create/Edit) ===
    'alert.modal.create': 'Neue Meldung erstellen',
    'alert.modal.edit': 'Meldung bearbeiten',
    'alert.modal.view': 'Meldung anzeigen',
    'alert.tabs.basics': 'Grunddaten',
    'alert.tabs.validity': 'Gültigkeit',
    'alert.tabs.references': 'Bezug',
    'alert.tabs.text': 'Text',
    'alert.cause': 'Ursache',
    'alert.effect': 'Auswirkung',
    'alert.severity': 'Schweregrad',
    'alert.active': 'Aktiv',
    'alert.active.yes': '✓ Aktiv',
    'alert.active.no': '✗ Inaktiv',
    'alert.view.status': 'Status',
    'alert.view.source': 'Quelle',
    'alert.view.source.internal': 'Intern (echogtfs)',
    'alert.cause.unknown': 'Unbekannte Ursache',
    'alert.cause.unknown.cause': 'Unbekannte Ursache',
    'alert.cause.other': 'Sonstige Ursache',
    'alert.cause.other.cause': 'Sonstige Ursache',
    'alert.cause.technical': 'Technisches Problem',
    'alert.cause.technical.problem': 'Technisches Problem',
    'alert.cause.strike': 'Streik',
    'alert.cause.demonstration': 'Demonstration',
    'alert.cause.accident': 'Unfall',
    'alert.cause.holiday': 'Feiertag',
    'alert.cause.weather': 'Wetter',
    'alert.cause.maintenance': 'Wartung',
    'alert.cause.construction': 'Bauarbeiten',
    'alert.cause.police': 'Polizeieinsatz',
    'alert.cause.police.activity': 'Polizeieinsatz',
    'alert.cause.medical': 'Medizinischer Notfall',
    'alert.cause.medical.emergency': 'Medizinischer Notfall',
    'alert.effect.unknown': 'Unbekannte Auswirkung',
    'alert.effect.unknown.effect': 'Unbekannte Auswirkung',
    'alert.effect.no.service': 'Kein Service',
    'alert.effect.reduced': 'Eingeschränkter Service',
    'alert.effect.reduced.service': 'Eingeschränkter Service',
    'alert.effect.delays': 'Erhebliche Verspätungen',
    'alert.effect.significant.delays': 'Erhebliche Verspätungen',
    'alert.effect.detour': 'Umleitung',
    'alert.effect.additional': 'Zusätzlicher Service',
    'alert.effect.additional.service': 'Zusätzlicher Service',
    'alert.effect.modified': 'Geänderter Service',
    'alert.effect.modified.service': 'Geänderter Service',
    'alert.effect.other': 'Sonstige Auswirkung',
    'alert.effect.other.effect': 'Sonstige Auswirkung',
    'alert.effect.stop.moved': 'Haltestelle verlegt',
    'alert.effect.stop_moved': 'Haltestelle verlegt',
    'alert.effect.no.effect': 'Keine Auswirkung',
    'alert.effect.no_effect': 'Keine Auswirkung',
    'alert.effect.accessibility': 'Barrierefreiheitsproblem',
    'alert.effect.accessibility.issue': 'Barrierefreiheitsproblem',
    'alert.severity.unknown': 'Unbekannt',
    'alert.severity.unknown.severity': 'Unbekannt',
    'alert.severity.info': 'Info',
    'alert.severity.warning': 'Warnung',
    'alert.severity.severe': 'Schwerwiegend',
    'alert.period.add': 'Zeitraum hinzufügen',
    'alert.period.title': 'Zeitraum {number}',
    'alert.period.start': 'Startzeit',
    'alert.period.start.label': 'Von (optional)',
    'alert.period.end': 'Endzeit',
    'alert.period.end.label': 'Bis (optional)',
    'alert.entity.add': 'Bezug hinzufügen',
    'alert.entity.title': 'Bezug {number}',
    'alert.entity.agency': 'Unternehmen',
    'alert.entity.route': 'Linie',
    'alert.entity.route_type': 'Linientyp',
    'alert.entity.route_type.placeholder': 'Typ auswählen...',
    'alert.entity.route_type.tram': 'Straßenbahn',
    'alert.entity.route_type.subway': 'U-Bahn',
    'alert.entity.route_type.rail': 'Zug',
    'alert.entity.route_type.bus': 'Bus',
    'alert.entity.route_type.ferry': 'Fähre',
    'alert.entity.route_type.cable_tram': 'Seilbahn',
    'alert.entity.route_type.aerial_lift': 'Gondel',
    'alert.entity.route_type.funicular': 'Standseilbahn',
    'alert.entity.route_type.trolleybus': 'Trolleybus',
    'alert.entity.route_type.monorail': 'Einschienenbahn',
    'alert.entity.direction': 'Fahrtrichtung',
    'alert.entity.direction.label': 'Richtung (optional)',
    'alert.entity.direction.placeholder': 'Richtung auswählen...',
    'alert.entity.direction.outbound': 'Hinfahrt',
    'alert.entity.direction.inbound': 'Rückfahrt',
    'alert.entity.stop': 'Haltestelle',
    'alert.entity.stop.label': 'Haltestelle (optional)',
    'alert.entity.agency.label': 'Unternehmen (optional)',
    'alert.entity.route.label': 'Linie (optional)',
    'alert.entity.route_type.label': 'Linientyp (optional)',
    'alert.entity.invalid.tooltip': 'Bezug konnte nicht aufgelöst werden',
    'alert.entity.label.agency': 'Unternehmen',
    'alert.entity.label.route': 'Linie',
    'alert.entity.label.route_type': 'Linientyp',
    'alert.entity.label.trip': 'Fahrt',
    'alert.entity.all_routes': 'Alle Verbindungen betroffen',
    'alert.period.always_valid': 'Dauerhaft gültig',
    'alert.translation.add': 'Übersetzung hinzufügen',
    'alert.translation.title': 'Übersetzung {number}',
    'alert.translation.language': 'Sprache',
    'alert.translation.language.de': 'Deutsch',
    'alert.translation.language.en': 'English',
    'alert.translation.language.fr': 'Français',
    'alert.translation.language.it': 'Italiano',
    'alert.translation.language.es': 'Español',
    'alert.translation.header': 'Titel',
    'alert.translation.desc': 'Beschreibung (optional)',
    'alert.translation.url': 'URL (optional)',
    'alert.translation.translations': 'Übersetzungen',
    'alert.error.translation_required': 'Bitte mindestens eine Übersetzung mit Titel eingeben.',
    
    // === SOURCES PANEL ===
    'sources.title': 'Datenquellen',
    'sources.add': '+ Hinzufügen',
    'sources.loading': 'Wird geladen ...',
    'sources.empty': 'Keine Datenquellen vorhanden.',
    'sources.error.load': 'Fehler beim Laden',
    'sources.error.notfound': 'Datenquelle nicht gefunden.',
    'sources.select_option': '-- Bitte auswählen --',
    'sources.table.name': 'Name',
    'sources.table.type': 'Typ',
    'sources.table.cron': 'Cron',
    'sources.table.lastrun': 'Letzte Ausführung',
    'sources.badge.inactive': 'Inaktiv',
    'sources.run.title': 'Jetzt ausführen',
    'sources.run.disabled': 'Quelle ist deaktiviert',
    'sources.run.started': 'Import von „{name}" wurde gestartet.',
    'sources.run.error.inactive': 'Diese Datenquelle ist deaktiviert und kann nicht ausgeführt werden.',
    'sources.activated': 'Datenquelle aktiviert.',
    'sources.deactivated': 'Datenquelle deaktiviert.',
    'sources.created': 'Datenquelle erstellt.',
    'sources.updated': 'Datenquelle aktualisiert.',
    'sources.deleted': 'Datenquelle gelöscht.',
    'sources.delete.confirm': 'Möchten Sie die Datenquelle „{name}" wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
    'sources.delete.title': 'Datenquelle löschen',
    
    // === SOURCES MODAL ===
    'source.modal.create': 'Neue Datenquelle',
    'source.modal.edit': 'Datenquelle bearbeiten',
    'source.tabs.configuration': 'Konfiguration',
    'source.tabs.mapping': 'Mapping',
    'source.name': 'Name',
    'source.type': 'Adapter-Typ',
    'source.type.placeholder': 'Typ auswählen...',
    'source.cron': 'Cron-Ausdruck (optional)',
    'source.cron.helper': 'z.B. 0 3 * * * für täglich um 3 Uhr',
    'source.invalid_reference_policy': 'Verfahrensweise bei ungültigen Bezügen',
    'source.invalid_reference_policy.helper': 'Definiert, wie mit Meldungen umgegangen wird, die auf nicht-existierende GTFS-Objekte verweisen.',
    'source.invalid_reference_policy.not_specified': 'keine Angabe',
    'source.invalid_reference_policy.discard_alert': 'gesamte Meldung verwerfen',
    'source.invalid_reference_policy.discard_invalid': 'ungültige Bezüge verwerfen',
    'source.invalid_reference_policy.discard_invalid_elements': 'ungültige Bezugselemente verwerfen',
    'source.invalid_reference_policy.keep_alert': 'gesamte Meldung deaktivieren',
    'source.active': 'Aktiv',
    'source.inactive.helper': 'Inaktive Datenquellen führen keine Importe durch und deren Meldungen werden gelöscht.',
    'source.error.required': 'Name und Typ sind erforderlich.',
    'source.error.save_first': 'Bitte speichern Sie die Datenquelle zuerst.',
    'source.error.enrichment_value_required': 'Bitte wählen Sie für alle Anreicherungen einen gültigen Wert aus.',
    'source.mapping.type': 'Mapping-Typ',
    'source.mapping.type.agency': 'Unternehmen',
    'source.mapping.type.route': 'Linien',
    'source.mapping.type.stop': 'Haltestellen',
    'source.mapping.add': 'Mapping hinzufügen',
    'source.mapping.export': 'nach CSV exportieren',
    'source.mapping.import': 'aus CSV importieren',
    'source.mapping.empty': 'Keine Mappings für {type} vorhanden.',
    'source.mapping.key': 'Schlüssel',
    'source.mapping.key.placeholder': 'z.B. externer Key',
    'source.mapping.value': 'Wert (Entity ID)',
    'source.mapping.value.placeholder': 'z.B. route_123',
    'source.mapping.exported': '{type}-Mappings erfolgreich exportiert.',
    'source.mapping.imported': '{count} {type}-Mappings erfolgreich importiert.',
    'source.mapping.import.error.size': 'Die Datei ist zu groß. Maximal 10 MB erlaubt.',
    'source.mapping.import.error.format': 'Bitte nur CSV-Dateien hochladen.',
    'source.mapping.import.error': 'Import fehlgeschlagen',
    
    // Source Enrichments
    'source.tabs.enrichment': 'Anreicherung',
    'source.enrichment.type': 'Anreicherungstyp',
    'source.enrichment.type.cause': 'Ursache',
    'source.enrichment.type.effect': 'Auswirkung',
    'source.enrichment.type.severity': 'Schweregrad',
    'source.enrichment.add': 'Wert hinzufügen',
    'source.enrichment.empty': 'Keine Anreicherungen für {type} vorhanden.',
    'source.enrichment.source_field': 'Quellfeld',
    'source.enrichment.source_field.header': 'Titel',
    'source.enrichment.source_field.description': 'Beschreibung',
    'source.enrichment.source_field.header_description': 'Titel & Beschreibung',
    'source.enrichment.key': 'Schlüssel (Text/Regex)',
    'source.enrichment.key.placeholder': 'z.B. Streik|Ausstand',
    'source.enrichment.value': 'Wert',
    'source.enrichment.value.placeholder': 'Wert auswählen...',
    'source.enrichment.sort_order': 'Priorität',
    'source.enrichment.sort_order.placeholder': '0',
    
    // === ACCOUNTS PANEL ===
    'accounts.title': 'Accounts',
    'accounts.add': '+ Neuer Account',
    'accounts.loading': 'Wird geladen ...',
    'accounts.empty': 'Keine Accounts vorhanden.',
    'accounts.error.load': 'Fehler beim Laden der Accounts.',
    'accounts.error.notfound': 'Account nicht gefunden.',
    'accounts.created': 'Account erstellt.',
    'accounts.updated': 'Account aktualisiert.',
    'accounts.deleted': 'Account „{name}" wurde gelöscht.',
    'accounts.delete.confirm': 'Account „{name}" wirklich löschen? Diese Aktion ist unwiderruflich.',
    'accounts.delete.title': 'Account löschen',
    'accounts.table.username': 'Benutzername',
    'accounts.table.email': 'E-Mail',
    'accounts.table.role': 'Rolle',
    'accounts.table.status': 'Status',
    'accounts.role.admin': 'Admin',
    'accounts.role.poweruser': 'Poweruser',
    'accounts.role.standard': 'Standard',
    'accounts.status.active': 'Aktiv',
    'accounts.status.inactive': 'Inaktiv',
    'accounts.edit.tooltip': 'Bearbeiten',
    'accounts.edit.aria': 'Account {name} bearbeiten',
    'accounts.delete.tooltip': 'Löschen',
    'accounts.delete.aria': 'Account {name} löschen',
    
    // === ACCOUNTS MODAL ===
    'account.modal.create': 'Neuer Account',
    'account.modal.edit': 'Account bearbeiten',
    'account.username': 'Benutzername',
    'account.email': 'E-Mail',
    'account.password': 'Passwort',
    'account.password.hint.create': '',
    'account.password.hint.edit': 'Leer lassen, um bestehendes Passwort beizubehalten',
    'account.active': 'Aktiv',
    'account.superuser': 'Admin',
    'account.poweruser': 'Poweruser',
    'account.chip.active': 'Aktiv',
    'account.chip.admin': 'Admin',
    'account.chip.poweruser': 'Poweruser',
    'account.chip.standard': 'Standard',
    'account.error.email_required': 'Bitte E-Mail eingeben.',
    'account.error.username_required': 'Bitte Benutzername eingeben.',
    'account.error.password_required': 'Bitte Passwort eingeben.',
    
    // === SETTINGS PANEL ===
    'settings.title': 'Einstellungen',
    'settings.section.general': 'Allgemein',
    'settings.section.appearance': 'Erscheinungsbild',
    'settings.section.language': 'Sprache',
    'settings.section.gtfs_realtime': 'GTFS-Realtime',
    'settings.section.gtfs_feed': 'GTFS-Feed',
    'settings.app_title': 'App-Titel',
    'settings.color_primary': 'Primärfarbe',
    'settings.color_primary.aria': 'Primärfarbe (Hex)',
    'settings.color_secondary': 'Sekundärfarbe',
    'settings.color_secondary.aria': 'Sekundärfarbe (Hex)',
    'settings.language': 'Sprache',
    'settings.language.de': 'Deutsch',
    'settings.language.en': 'English',
    'settings.gtfs_rt_path': 'GTFS-RT Endpunkt-Pfad',
    'settings.gtfs_rt_path.helper': 'Pfad ohne /api/ Präfix, z.B. realtime/service-alerts.pbf',
    'settings.gtfs_rt_username': 'Basic Auth Benutzername (optional)',
    'settings.gtfs_rt_username.helper': 'Beide Felder löschen, um Basic Auth zu deaktivieren',
    'settings.gtfs_rt_password': 'Basic Auth Passwort (optional)',
    'settings.gtfs_rt_password.helper': 'Leer lassen für neues Passwort oder altes Passwort behalten',
    'settings.reset': 'Zurücksetzen',
    'settings.save': 'Speichern',
    'settings.saved': 'Einstellungen gespeichert.',
    'settings.reset.confirm': 'Möchten Sie wirklich alle Einstellungen auf die Standardwerte zurücksetzen?',
    'settings.reset.title': 'Einstellungen zurücksetzen',
    'settings.reset.done': 'Einstellungen zurückgesetzt.',
    'settings.gtfs_url': 'Feed-URL (GTFS Static ZIP)',
    'settings.gtfs_cron': 'Cron-Ausdruck für automatischen Import',
    'settings.gtfs_cron.helper': 'z.B. 0 3 * * * für täglich um 3 Uhr',
    'settings.gtfs_import': 'Importieren',
    'settings.gtfs_save': 'Speichern',
    'settings.gtfs_url_saved': 'Feed-URL und Cron gespeichert.',
    'settings.gtfs_import_running': 'Import läuft …',
    'settings.gtfs_import_success': 'GTFS-Import erfolgreich abgeschlossen.',
    'settings.gtfs_import_error': 'GTFS-Import fehlgeschlagen. Siehe Status-Details.',
    'settings.gtfs_import_last': 'Letzter Import: {time}',
    'settings.gtfs_import_last_short': 'Letzter Import: {time}',
    'settings.gtfs_import_error_time': 'Fehler ({time}): {message}',
    'settings.gtfs_import_error_short': 'Fehler: {message}',
    'settings.gtfs_import_none': 'Noch kein Import durchgeführt.',
    'settings.gtfs_import_url_required': 'Bitte zuerst eine gültige Feed-URL eingeben.',
    
    // === CONFIRM MODAL ===
    'confirm.title': 'Bestätigung erforderlich',
    'confirm.cancel': 'Abbrechen',
    'confirm.ok': 'Löschen',
    
    // === ERRORS (API) ===
    'error.invalid_credentials': 'Ungültige Anmeldedaten.',
    'error.user_not_found': 'Benutzer nicht gefunden.',
    'error.user_exists': 'Benutzer existiert bereits.',
    'error.required_fields': 'Erforderliche Felder fehlen.',
    'error.invalid_email': 'Ungültiges E-Mail-Format.',
    'error.password_short': 'Passwort zu kurz.',
    'error.access_denied': 'Zugriff verweigert.',
    'error.source_not_found': 'Datenquelle nicht gefunden.',
    'error.invalid_cron': 'Ungültiger Cron-Ausdruck.',
    'error.alert_not_found': 'Meldung nicht gefunden.',
    'error.cannot_delete_external': 'Externe Meldungen können nicht gelöscht werden.',
    'error.invalid_period': 'Ungültiger Aktivierungszeitraum.',
    'error.missing_translation': 'Übersetzung fehlt.',
    'error.invalid_entity': 'Ungültiger Bezug.',
    'error.invalid_input': 'Die Eingabedaten sind ungültig. Bitte überprüfen Sie Ihre Eingaben.',
    'error.conflict': 'Konflikt: Die angeforderte Änderung ist nicht möglich.',
    'error.server_500': 'Interner Serverfehler. Bitte versuchen Sie es später erneut.',
    'error.server_503': 'Der Server ist vorübergehend nicht verfügbar.',
    'error.request_failed': 'Anfrage fehlgeschlagen.',
    'error.server_error': 'Serverfehler. Bitte wenden Sie sich an den Administrator.',
    'error.unknown': 'Ein unbekannter Fehler ist aufgetreten.',
    'error.network': 'Der Server ist nicht erreichbar. Bitte überprüfen Sie Ihre Internetverbindung.',
    
    // === PLACEHOLDERS ===
    'placeholder.empty': 'Keine Einträge vorhanden.',
    
    // === ADAPTER CONFIGS ===
    // GTFS-Realtime Adapter
    'adapter.gtfsrt.endpoint.label': 'Endpoint URL',
    'adapter.gtfsrt.endpoint.placeholder': 'https://api.example.com/gtfs-realtime',
    'adapter.gtfsrt.endpoint.help_text': 'URL zum GTFS-Realtime Protobuf Feed',
    'adapter.gtfsrt.token.label': 'API Token (optional)',
    'adapter.gtfsrt.token.placeholder': 'Bearer-Token oder API-Key',
    'adapter.gtfsrt.token.help_text': 'Authentifizierungs-Token für die API (falls erforderlich)',
    
    // SIRI-Lite Adapter
    'adapter.sirilite.endpoint.label': 'Endpoint URL',
    'adapter.sirilite.endpoint.placeholder': 'https://api.example.com/siri-lite',
    'adapter.sirilite.endpoint.help_text': 'URL zum SIRI-Lite Feed',
    'adapter.sirilite.token.label': 'API Token (optional)',
    'adapter.sirilite.token.placeholder': 'Bearer-Token oder API-Key',
    'adapter.sirilite.token.help_text': 'Authentifizierungs-Token für die API (falls erforderlich)',
    'adapter.sirilite.dialect.label': 'Dialekt',
    'adapter.sirilite.dialect.help_text': 'Regionale Implementierungsvariante',
    'adapter.sirilite.dialect.option.swiss': 'Swiss',
    'adapter.sirilite.dialect.option.sirisx': 'SIRI-SX',
    'adapter.sirilite.filter.label': 'Filter',
    'adapter.sirilite.filter.placeholder': 'Optionaler Filter-Ausdruck',
    'adapter.sirilite.filter.help_text': 'Filter zur Einschränkung der Datenquelle',
    
    // SIRI-SX Adapter
    'adapter.sirisx.endpoint.label': 'Endpoint URL',
    'adapter.sirisx.endpoint.placeholder': 'https://api.example.com/siri-sx?RequestorRef={participantRef}',
    'adapter.sirisx.endpoint.help_text': 'URL zum SIRI-SX Feed',
    'adapter.sirisx.participantref.label': 'Participant Reference',
    'adapter.sirisx.participantref.placeholder': 'YOUR_PARTICIPANT_ID',
    'adapter.sirisx.participantref.help_text': 'Leitstellenkennung',
    'adapter.sirisx.method.label': 'Methode',
    'adapter.sirisx.method.help_text': 'Anfrage-Methode (Request/Response oder Publish/Subscribe)',
    'adapter.sirisx.method.option.request_response': 'Request/Response',
    'adapter.sirisx.method.option.publish_subscribe': 'Publish/Subscribe',
    'adapter.sirisx.dialect.label': 'Dialekt',
    'adapter.sirisx.dialect.help_text': 'Regionale Implementierungsvariante (SIRI-SX)',
    'adapter.sirisx.dialect.option.sirisx': 'SIRI-SX',
    'adapter.sirisx.filter.label': 'Filter',
    'adapter.sirisx.filter.placeholder': 'Optionaler Filter-Ausdruck',
    'adapter.sirisx.filter.help_text': 'Filter zur Einschränkung der Datenquelle',
  },
  
  en: {
    // === LOGIN ===
    'login.title': 'Sign In',
    'login.subtitle': 'Please sign in',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.button': 'Sign In',
    'login.button.busy': 'Signing in…',
    
    // === LOADING & COMMON ===
    'loading.screen': 'Loading',
    'loading.default': 'Loading...',
    'loading.saving': 'Saving...',
    'loading.importing': 'Importing…',
    
    // === COMMON ACTIONS ===
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.remove.title': 'Remove',
    'common.reset': 'Reset',
    'common.view': 'View',
    'common.activate': 'Activate',
    'common.deactivate': 'Deactivate',
    'common.run': 'Run now',
    'common.import': 'Import',
    'common.export': 'Export',
    'common.move_up': 'Move up',
    'common.move_down': 'Move down',
    
    // === NAVIGATION ===
    'nav.main': 'Main navigation',
    'nav.alerts': 'Alerts',
    'nav.sources': 'Data Sources',
    'nav.accounts': 'Accounts',
    'nav.settings': 'Settings',
    'nav.logout': 'Sign Out',
    
    // === TOP BAR ===
    'topbar.language.title': 'Switch language',
    'topbar.language.label': 'Language',
    'topbar.language.de': 'Deutsch',
    'topbar.language.en': 'English',
    'topbar.logout.title': 'Sign Out',
    'topbar.logout.label': 'Sign Out',
    
    // === ALERTS PANEL ===
    'alerts.title': 'Alerts',
    'alerts.quickfilter': 'Quick filter',
    'alerts.quickfilter.placeholder': 'Enter search term...',
    'alerts.sort.newest': 'newest first',
    'alerts.sort.oldest': 'oldest first',
    'alerts.sort.title': 'Reverse sort order',
    'alerts.filter': 'Filter',
    'alerts.filter.status': 'Status',
    'alerts.filter.status.active': 'active alerts',
    'alerts.filter.status.inactive': 'inactive alerts',
    'alerts.filter.source': 'Source',
    'alerts.filter.source.internal': 'internal alerts',
    'alerts.filter.source.external': 'external alerts',
    'alerts.add': '+ Create',
    'alerts.loading': 'Loading...',
    'alerts.empty': 'No alerts available yet.',
    'alerts.empty.filter': 'No alerts match the filter.',
    'alerts.error.load': 'Error loading alerts.',
    'alerts.error.notfound': 'Alert not found.',
    'alerts.badge.internal': 'Internal',
    'alerts.badge.external': 'External',
    'alerts.badge.inactive': 'Inactive',
    'alerts.status.changed': 'Alert status changed.',
    'alerts.created': 'Alert created.',
    'alerts.updated': 'Alert updated.',
    'alerts.deleted': 'Alert "{name}" has been deleted.',
    'alerts.delete.confirm': 'Really delete alert "{name}"? This action cannot be undone.',
    'alerts.delete.title': 'Delete Alert',
    'alerts.title.notitle': 'No title',
    'alerts.title.unnamed': 'Unnamed Alert',
    'alerts.resolution.warning': 'Some references could not be resolved',
    'alerts.pagination.info': 'Page {current} of {total} ({count} alerts)',
    
    // === ALERTS MODAL (Create/Edit) ===
    'alert.modal.create': 'Create New Alert',
    'alert.modal.edit': 'Edit Alert',
    'alert.modal.view': 'View Alert',
    'alert.tabs.basics': 'Basics',
    'alert.tabs.validity': 'Validity',
    'alert.tabs.references': 'References',
    'alert.tabs.text': 'Text',
    'alert.cause': 'Cause',
    'alert.effect': 'Effect',
    'alert.severity': 'Severity',
    'alert.active': 'Active',
    'alert.active.yes': '✓ Active',
    'alert.active.no': '✗ Inactive',
    'alert.view.status': 'Status',
    'alert.view.source': 'Source',
    'alert.view.source.internal': 'Internal (echogtfs)',
    'alert.cause.unknown': 'Unknown cause',
    'alert.cause.unknown.cause': 'Unknown cause',
    'alert.cause.other': 'Other cause',
    'alert.cause.other.cause': 'Other cause',
    'alert.cause.technical': 'Technical problem',
    'alert.cause.technical.problem': 'Technical problem',
    'alert.cause.strike': 'Strike',
    'alert.cause.demonstration': 'Demonstration',
    'alert.cause.accident': 'Accident',
    'alert.cause.holiday': 'Holiday',
    'alert.cause.weather': 'Weather',
    'alert.cause.maintenance': 'Maintenance',
    'alert.cause.construction': 'Construction',
    'alert.cause.police': 'Police activity',
    'alert.cause.police.activity': 'Police activity',
    'alert.cause.medical': 'Medical emergency',
    'alert.cause.medical.emergency': 'Medical emergency',
    'alert.effect.unknown': 'Unknown effect',
    'alert.effect.unknown.effect': 'Unknown effect',
    'alert.effect.no.service': 'No service',
    'alert.effect.reduced': 'Reduced service',
    'alert.effect.reduced.service': 'Reduced service',
    'alert.effect.delays': 'Significant delays',
    'alert.effect.significant.delays': 'Significant delays',
    'alert.effect.detour': 'Detour',
    'alert.effect.additional': 'Additional service',
    'alert.effect.additional.service': 'Additional service',
    'alert.effect.modified': 'Modified service',
    'alert.effect.modified.service': 'Modified service',
    'alert.effect.other': 'Other effect',
    'alert.effect.other.effect': 'Other effect',
    'alert.effect.stop.moved': 'Stop moved',
    'alert.effect.stop_moved': 'Stop moved',
    'alert.effect.no.effect': 'No effect',
    'alert.effect.no_effect': 'No effect',
    'alert.effect.accessibility': 'Accessibility issue',
    'alert.effect.accessibility.issue': 'Accessibility issue',
    'alert.severity.unknown': 'Unknown',
    'alert.severity.unknown.severity': 'Unknown',
    'alert.severity.info': 'Info',
    'alert.severity.warning': 'Warning',
    'alert.severity.severe': 'Severe',
    'alert.period.add': 'Add time period',
    'alert.period.title': 'Period {number}',
    'alert.period.start': 'Start time',
    'alert.period.start.label': 'From (optional)',
    'alert.period.end': 'End time',
    'alert.period.end.label': 'To (optional)',
    'alert.entity.add': 'Add reference',
    'alert.entity.title': 'Reference {number}',
    'alert.entity.agency': 'Agency',
    'alert.entity.route': 'Route',
    'alert.entity.route_type': 'Route type',
    'alert.entity.route_type.placeholder': 'Select type...',
    'alert.entity.route_type.tram': 'Tram',
    'alert.entity.route_type.subway': 'Subway',
    'alert.entity.route_type.rail': 'Rail',
    'alert.entity.route_type.bus': 'Bus',
    'alert.entity.route_type.ferry': 'Ferry',
    'alert.entity.route_type.cable_tram': 'Cable tram',
    'alert.entity.route_type.aerial_lift': 'Aerial lift',
    'alert.entity.route_type.funicular': 'Funicular',
    'alert.entity.route_type.trolleybus': 'Trolleybus',
    'alert.entity.route_type.monorail': 'Monorail',
    'alert.entity.direction': 'Direction',
    'alert.entity.direction.label': 'Direction (optional)',
    'alert.entity.direction.placeholder': 'Select direction...',
    'alert.entity.direction.outbound': 'Outbound',
    'alert.entity.direction.inbound': 'Inbound',
    'alert.entity.stop': 'Stop',
    'alert.entity.stop.label': 'Stop (optional)',
    'alert.entity.agency.label': 'Agency (optional)',
    'alert.entity.route.label': 'Route (optional)',
    'alert.entity.route_type.label': 'Route type (optional)',
    'alert.entity.invalid.tooltip': 'Reference could not be resolved',
    'alert.entity.label.agency': 'Agency',
    'alert.entity.label.route': 'Route',
    'alert.entity.label.route_type': 'Route type',
    'alert.entity.label.trip': 'Trip',
    'alert.entity.all_routes': 'All routes affected',
    'alert.period.always_valid': 'Always valid',
    'alert.translation.add': 'Add translation',
    'alert.translation.title': 'Translation {number}',
    'alert.translation.language': 'Language',
    'alert.translation.language.de': 'Deutsch',
    'alert.translation.language.en': 'English',
    'alert.translation.language.fr': 'Français',
    'alert.translation.language.it': 'Italiano',
    'alert.translation.language.es': 'Español',
    'alert.translation.header': 'Title',
    'alert.translation.desc': 'Description (optional)',
    'alert.translation.url': 'URL (optional)',
    'alert.translation.translations': 'Translations',
    'alert.error.translation_required': 'Please enter at least one translation with a title.',
    
    // === SOURCES PANEL ===
    'sources.title': 'Data Sources',
    'sources.add': '+ Add',
    'sources.loading': 'Loading...',
    'sources.empty': 'No data sources available.',
    'sources.error.load': 'Error loading',
    'sources.error.notfound': 'Data source not found.',
    'sources.select_option': '-- Please select --',
    'sources.table.name': 'Name',
    'sources.table.type': 'Type',
    'sources.table.cron': 'Cron',
    'sources.table.lastrun': 'Last run',
    'sources.badge.inactive': 'Inactive',
    'sources.run.title': 'Run now',
    'sources.run.disabled': 'Source is disabled',
    'sources.run.started': 'Import of "{name}" has been started.',
    'sources.run.error.inactive': 'This data source is disabled and cannot be run.',
    'sources.activated': 'Data source activated.',
    'sources.deactivated': 'Data source deactivated.',
    'sources.created': 'Data source created.',
    'sources.updated': 'Data source updated.',
    'sources.deleted': 'Data source deleted.',
    'sources.delete.confirm': 'Do you really want to delete the data source "{name}"? This action cannot be undone.',
    'sources.delete.title': 'Delete Data Source',
    
    // === SOURCES MODAL ===
    'source.modal.create': 'New Data Source',
    'source.modal.edit': 'Edit Data Source',
    'source.tabs.configuration': 'Configuration',
    'source.tabs.mapping': 'Mapping',
    'source.name': 'Name',
    'source.type': 'Adapter type',
    'source.type.placeholder': 'Select type...',
    'source.cron': 'Cron expression (optional)',
    'source.cron.helper': 'e.g., 0 3 * * * for daily at 3 AM',
    'source.invalid_reference_policy': 'Invalid reference policy',
    'source.invalid_reference_policy.helper': 'Defines how to handle alerts that reference non-existent GTFS objects.',
    'source.invalid_reference_policy.not_specified': 'not specified',
    'source.invalid_reference_policy.discard_alert': 'discard entire alert',
    'source.invalid_reference_policy.discard_invalid': 'discard invalid references',
    'source.invalid_reference_policy.discard_invalid_elements': 'discard invalid reference elements',
    'source.invalid_reference_policy.keep_alert': 'deactivate entire alert',
    'source.active': 'Active',
    'source.inactive.helper': 'Inactive data sources do not perform imports and their alerts are deleted.',
    'source.error.required': 'Name and type are required.',
    'source.error.save_first': 'Please save the data source first.',
    'source.error.enrichment_value_required': 'Please select a valid value for all enrichments.',
    'source.mapping.type': 'Mapping type',
    'source.mapping.type.agency': 'Agencies',
    'source.mapping.type.route': 'Routes',
    'source.mapping.type.stop': 'Stops',
    'source.mapping.add': 'Add mapping',
    'source.mapping.export': 'export to CSV',
    'source.mapping.import': 'import from CSV',
    'source.mapping.empty': 'No mappings for {type} available.',
    'source.mapping.key': 'Key',
    'source.mapping.key.placeholder': 'e.g., external key',
    'source.mapping.value': 'Value (Entity ID)',
    'source.mapping.value.placeholder': 'e.g., route_123',
    'source.mapping.exported': '{type} mappings successfully exported.',
    'source.mapping.imported': '{count} {type} mappings successfully imported.',
    'source.mapping.import.error.size': 'File is too large. Maximum 10 MB allowed.',
    'source.mapping.import.error.format': 'Please upload CSV files only.',
    'source.mapping.import.error': 'Import failed',
    
    // Source Enrichments
    'source.tabs.enrichment': 'Enrichment',
    'source.enrichment.type': 'Enrichment type',
    'source.enrichment.type.cause': 'Cause',
    'source.enrichment.type.effect': 'Effect',
    'source.enrichment.type.severity': 'Severity',
    'source.enrichment.add': 'Add value',
    'source.enrichment.empty': 'No enrichments for {type} available.',
    'source.enrichment.source_field': 'Source field',
    'source.enrichment.source_field.header': 'Title',
    'source.enrichment.source_field.description': 'Description',
    'source.enrichment.source_field.header_description': 'Title & Description',
    'source.enrichment.key': 'Key (text/regex)',
    'source.enrichment.key.placeholder': 'e.g., strike|walkout',
    'source.enrichment.value': 'Value',
    'source.enrichment.value.placeholder': 'Select value...',
    'source.enrichment.sort_order': 'Priority',
    'source.enrichment.sort_order.placeholder': '0',
    
    // === ACCOUNTS PANEL ===
    'accounts.title': 'Accounts',
    'accounts.add': '+ New Account',
    'accounts.loading': 'Loading...',
    'accounts.empty': 'No accounts available.',
    'accounts.error.load': 'Error loading accounts.',
    'accounts.error.notfound': 'Account not found.',
    'accounts.created': 'Account created.',
    'accounts.updated': 'Account updated.',
    'accounts.deleted': 'Account "{name}" has been deleted.',
    'accounts.delete.confirm': 'Really delete account "{name}"? This action cannot be undone.',
    'accounts.delete.title': 'Delete Account',
    'accounts.table.username': 'Username',
    'accounts.table.email': 'Email',
    'accounts.table.role': 'Role',
    'accounts.table.status': 'Status',
    'accounts.role.admin': 'Admin',
    'accounts.role.poweruser': 'Poweruser',
    'accounts.role.standard': 'Standard',
    'accounts.status.active': 'Active',
    'accounts.status.inactive': 'Inactive',
    'accounts.edit.tooltip': 'Edit',
    'accounts.edit.aria': 'Edit account {name}',
    'accounts.delete.tooltip': 'Delete',
    'accounts.delete.aria': 'Delete account {name}',
    
    // === ACCOUNTS MODAL ===
    'account.modal.create': 'New Account',
    'account.modal.edit': 'Edit Account',
    'account.username': 'Username',
    'account.email': 'Email',
    'account.password': 'Password',
    'account.password.hint.create': '',
    'account.password.hint.edit': 'Leave empty to keep existing password',
    'account.active': 'Active',
    'account.superuser': 'Admin',
    'account.poweruser': 'Poweruser',
    'account.chip.active': 'Active',
    'account.chip.admin': 'Admin',
    'account.chip.poweruser': 'Poweruser',
    'account.chip.standard': 'Standard',
    'account.error.email_required': 'Please enter an email.',
    'account.error.username_required': 'Please enter a username.',
    'account.error.password_required': 'Please enter a password.',
    
    // === SETTINGS PANEL ===
    'settings.title': 'Settings',
    'settings.section.general': 'General',
    'settings.section.appearance': 'Appearance',
    'settings.section.language': 'Language',
    'settings.section.gtfs_realtime': 'GTFS Realtime',
    'settings.section.gtfs_feed': 'GTFS Feed',
    'settings.app_title': 'App Title',
    'settings.color_primary': 'Primary color',
    'settings.color_primary.aria': 'Primary color (Hex)',
    'settings.color_secondary': 'Secondary color',
    'settings.color_secondary.aria': 'Secondary color (Hex)',
    'settings.language': 'Language',
    'settings.language.de': 'Deutsch',
    'settings.language.en': 'English',
    'settings.gtfs_rt_path': 'GTFS-RT endpoint path',
    'settings.gtfs_rt_path.helper': 'Path without /api/ prefix, e.g., realtime/service-alerts.pbf',
    'settings.gtfs_rt_username': 'Basic Auth username (optional)',
    'settings.gtfs_rt_username.helper': 'Clear both fields to disable Basic Auth',
    'settings.gtfs_rt_password': 'Basic Auth password (optional)',
    'settings.gtfs_rt_password.helper': 'Leave empty to set new password or keep old password',
    'settings.reset': 'Reset',
    'settings.save': 'Save',
    'settings.saved': 'Settings saved.',
    'settings.reset.confirm': 'Do you really want to reset all settings to their default values?',
    'settings.reset.title': 'Reset Settings',
    'settings.reset.done': 'Settings reset.',
    'settings.gtfs_url': 'Feed URL (GTFS Static ZIP)',
    'settings.gtfs_cron': 'Cron expression for automatic import',
    'settings.gtfs_cron.helper': 'e.g., 0 3 * * * for daily at 3 AM',
    'settings.gtfs_import': 'Import',
    'settings.gtfs_save': 'Save',
    'settings.gtfs_url_saved': 'Feed URL and cron saved.',
    'settings.gtfs_import_running': 'Import running…',
    'settings.gtfs_import_success': 'GTFS import completed successfully.',
    'settings.gtfs_import_error': 'GTFS import failed. See status details.',
    'settings.gtfs_import_last': 'Last import: {time}',
    'settings.gtfs_import_last_short': 'Last import: {time}',
    'settings.gtfs_import_error_time': 'Error ({time}): {message}',
    'settings.gtfs_import_error_short': 'Error: {message}',
    'settings.gtfs_import_none': 'No import performed yet.',
    'settings.gtfs_import_url_required': 'Please enter a valid feed URL first.',
    
    // === CONFIRM MODAL ===
    'confirm.title': 'Confirmation required',
    'confirm.cancel': 'Cancel',
    'confirm.ok': 'Delete',
    
    // === ERRORS (API) ===
    'error.invalid_credentials': 'Invalid credentials.',
    'error.user_not_found': 'User not found.',
    'error.user_exists': 'User already exists.',
    'error.required_fields': 'Required fields are missing.',
    'error.invalid_email': 'Invalid email format.',
    'error.password_short': 'Password too short.',
    'error.access_denied': 'Access denied.',
    'error.source_not_found': 'Data source not found.',
    'error.invalid_cron': 'Invalid cron expression.',
    'error.alert_not_found': 'Alert not found.',
    'error.cannot_delete_external': 'External alerts cannot be deleted.',
    'error.invalid_period': 'Invalid time period.',
    'error.missing_translation': 'Translation missing.',
    'error.invalid_entity': 'Invalid reference.',
    'error.invalid_input': 'The input data is invalid. Please check your entries.',
    'error.conflict': 'Conflict: The requested change is not possible.',
    'error.server_500': 'Internal server error. Please try again later.',
    'error.server_503': 'The server is temporarily unavailable.',
    'error.request_failed': 'Request failed.',
    'error.server_error': 'Server error. Please contact the administrator.',
    'error.unknown': 'An unknown error occurred.',
    'error.network': 'The server is not reachable. Please check your internet connection.',
    
    // === PLACEHOLDERS ===
    'placeholder.empty': 'No entries available.',
    
    // === ADAPTER CONFIGS ===
    // GTFS-Realtime Adapter
    'adapter.gtfsrt.endpoint.label': 'Endpoint URL',
    'adapter.gtfsrt.endpoint.placeholder': 'https://api.example.com/gtfs-realtime',
    'adapter.gtfsrt.endpoint.help_text': 'URL to the GTFS-Realtime Protobuf feed',
    'adapter.gtfsrt.token.label': 'API Token (optional)',
    'adapter.gtfsrt.token.placeholder': 'Bearer token or API key',
    'adapter.gtfsrt.token.help_text': 'Authentication token for the API (if required)',
    
    // SIRI-Lite Adapter
    'adapter.sirilite.endpoint.label': 'Endpoint URL',
    'adapter.sirilite.endpoint.placeholder': 'https://api.example.com/siri-lite',
    'adapter.sirilite.endpoint.help_text': 'URL to the SIRI-Lite feed',
    'adapter.sirilite.token.label': 'API Token (optional)',
    'adapter.sirilite.token.placeholder': 'Bearer token or API key',
    'adapter.sirilite.token.help_text': 'Authentication token for the API (if required)',
    'adapter.sirilite.dialect.label': 'Dialect',
    'adapter.sirilite.dialect.help_text': 'Regional implementation variant',
    'adapter.sirilite.dialect.option.swiss': 'Swiss',
    'adapter.sirilite.dialect.option.sirisx': 'SIRI-SX',
    'adapter.sirilite.filter.label': 'Filter',
    'adapter.sirilite.filter.placeholder': 'Optional filter expression',
    'adapter.sirilite.filter.help_text': 'Filter to restrict the data source',
    
    // SIRI-SX Adapter
    'adapter.sirisx.endpoint.label': 'Endpoint URL',
    'adapter.sirisx.endpoint.placeholder': 'https://api.example.com/siri-sx?RequestorRef={participantRef}',
    'adapter.sirisx.endpoint.help_text': 'URL to the SIRI-SX feed',
    'adapter.sirisx.participantref.label': 'Participant Reference',
    'adapter.sirisx.participantref.placeholder': 'YOUR_PARTICIPANT_ID',
    'adapter.sirisx.participantref.help_text': 'Participant identifier',
    'adapter.sirisx.method.label': 'Method',
    'adapter.sirisx.method.help_text': 'Request method (Request/Response or Publish/Subscribe)',
    'adapter.sirisx.method.option.request_response': 'Request/Response',
    'adapter.sirisx.method.option.publish_subscribe': 'Publish/Subscribe',
    'adapter.sirisx.dialect.label': 'Dialect',
    'adapter.sirisx.dialect.help_text': 'Regional implementation variant (SIRI-SX)',
    'adapter.sirisx.dialect.option.sirisx': 'SIRI-SX',
    'adapter.sirisx.filter.label': 'Filter',
    'adapter.sirisx.filter.placeholder': 'Optional filter expression',
    'adapter.sirisx.filter.help_text': 'Filter to restrict the data source',
  }
};
